'''
This script generates assembly routines to select a memory configuration
for the Ultimem for a logical "bank".
This is done by configuring the Ultimem's registers ($9ff0-$9fff) for the
appropriate RAM/ROM and block selection.
'''

class Rom:
	def __init__(self, i):
		self.val = i
		self.cfg = 0x01	# %01

class Ram:
	def __init__(self, i):
		self.val = i
		self.cfg = 0x03	# %11

class Bank:
	def __init__(self, blk1, blk2, blk3, blk5):
		self.blk1 = blk1
		self.blk2 = blk2
		self.blk3 = blk3
		self.blk5 = blk5

segments = {
	"MAIN": Bank(
		blk1 = Rom(1),
		blk2 = Rom(2),
		blk3 = Rom(3),
		blk5 = Rom(4)
	),
	"DEBUG": Bank(
		blk1 = Ram(2),
		blk2 = Ram(3),
		blk3 = Ram(4),
		blk5 = Rom(5)
	),
	"UDGEDIT": Bank(
		blk1 = Ram(5),
		blk2 = Ram(6),
		blk3 = Ram(7),
		blk5 = Rom(6)
	),
	"EXPR": Bank(
		blk1 = Ram(5),
		blk2 = Ram(6),
		blk3 = Ram(7),
		blk5 = Rom(6)
	),
	"MACRO": Bank(
		blk1 = Ram(8),
		blk2 = Ram(9),
		blk3 = Ram(10),
		blk5 = Rom(7),
	),
	"LINKER": Bank(
		blk1 = Ram(11),
		blk2 = Ram(12),
		blk3 = Ram(13),
		blk5 = Rom(8),
	),
	"COPYBUFF": Bank(
		blk1 = Ram(14),
		blk2 = Ram(15),
		blk3 = Ram(16),
		blk5 = Rom(9),
	),
	"CONSOLE": Bank(
		blk1 = Ram(17),
		blk2 = Ram(18),
		blk3 = Ram(19),
		blk5 = Rom(10),
	),
	"SYMBOLS": Bank(
		blk1 = Ram(20),
		blk2 = Ram(21),
		blk3 = Ram(22),
		blk5 = Rom(11),
	),
	"SYMBOL_NAMES": Bank(
		blk1 = Ram(23),
		blk2 = Ram(24),
		blk3 = Ram(25),
		blk5 = Rom(11),
	),
	"CTX": Bank(
		blk1 = Ram(26),
		blk2 = Ram(27),
		blk3 = Ram(28),
		blk5 = Rom(12),
	),
	"VSCREEN": Bank(
		blk1 = Ram(29),
		blk2 = Ram(30),
		blk3 = Ram(31),
		blk5 = Rom(13),
	),
	"VSYS": Bank(
		blk1 = Ram(33),	# $0000-$2000    (virtual internal)
		blk2 = Ram(37), # $8000-$a000    (virutal I/O)
		blk3 = Ram(32), # backup for debugger RAM
		blk5 = Rom(14),
	),
	"FTXT": Bank(
		blk1 = Rom(16),
		blk2 = Rom(17),
		blk3 = Rom(18),
		blk5 = Rom(19),
	),
	# bank 31-34 stores user's program
	"USER": Bank(
		blk1 = Ram(33),
		blk2 = Ram(34),
		blk3 = Ram(35),
		blk5 = Ram(36),
	),
}

print("\n;*******************************************************************************")
print(  "; BANK MAPPINGS")
print(  "; Generated by genmapper.py")
print(";*******************************************************************************")

print("\n;*******************************************************************************")
print(";VIRTUAL BANK IDs")

# build the parallel configuration lists
blk1, blk2, blk3, blk5, cfg = [], [], [], [], []
idx = 1
for name, s in segments.items():
	# print the ID for this block
	print(("{:<20}".format(f"FINAL_BANK_{name}")) + f"= ${idx:02x}")

	blk1.append(s.blk1.val)
	blk2.append(s.blk2.val)
	blk3.append(s.blk3.val)
	blk5.append(s.blk5.val)

	# get the config based on the RAM/ROM selection
	cfg.append(
		(s.blk1.cfg << 0) |
		(s.blk2.cfg << 2) |
		(s.blk3.cfg << 4) |
		(s.blk5.cfg << 6)
	)
	idx += 1

# create the byte arrays for the bank configurations
print("\n;*******************************************************************************")
print("; VIRTUAL BANK CONFIG MAP")
print("; generated by genmapper.py")
print("blk1: .byte " + ", ".join(f"${v:02x}" for v in blk1))
print("blk2: .byte " + ", ".join(f"${v:02x}" for v in blk2))
print("blk3: .byte " + ", ".join(f"${v:02x}" for v in blk3))
print("blk5: .byte " + ", ".join(f"${v:02x}" for v in blk5))
print("cfg:  .byte " + ", ".join(f"${v:02x}" for v in cfg))
