.import __gui_active_type
.import __gui_baserow
.import __gui_close
.import __gui_closeall
.import __gui_cursave_x
.import __gui_cursave_y
.import __gui_enter
.import __gui_grow
.import __gui_maximize
.import __gui_open
.import __gui_refresh
.import __gui_select
.import __gui_shrink
.import __gui_togglehide

.scope gui
	active_type	= __gui_active_type
	baserow		= __gui_baserow
	close		= __gui_close
	closeall	= __gui_closeall
	cursave_x	= __gui_cursave_x
	cursave_y	= __gui_cursave_y
	enter		= __gui_enter
	grow		= __gui_grow
	maximize	= __gui_maximize
	open		= __gui_open
	refresh		= __gui_refresh
	select		= __gui_select
	shrink		= __gui_shrink
	togglehide	= __gui_togglehide
.endscope
