.import __kernal_talk
.import __kernal_tksa
.import __kernal_acptr
.import __kernal_untlk
.import __kernal_listen
.import __kernal_second
.import __kernal_unlsn
.import __kernal_chrin
.import __kernal_chrout
.import __kernal_readst
.import __kernal_setnam
.import __kernal_setlfs
.import __kernal_load
.import __kernal_chkin
.import __kernal_chkout
.import __kernal_ciout
.import __kernal_open
.import __kernal_close
.import __kernal_clall
.import __kernal_clrchn

.scope krn
	talk = __kernal_talk
	tksa = __kernal_tksa
	acptr = __kernal_acptr
	untlk = __kernal_untlk
	listen = __kernal_listen
	second = __kernal_second
	unlsn = __kernal_unlsn

	chrin  = __kernal_chrin
	chrout = __kernal_chrout
	readst = __kernal_readst
	setnam = __kernal_setnam
	setlfs = __kernal_setlfs
	load   = __kernal_load
	chkin  = __kernal_chkin
	chkout = __kernal_chkout
	ciout  = __kernal_ciout
	open   = __kernal_open
	close  = __kernal_close
	clall  = __kernal_clall
	clrchn = __kernal_clrchn
.endscope
