;*******************************************************************************
; LINKER.ASM
; The linker links the object code generated by the assembler into a binary
; (.prg or plain) or debug (.d) file.
;
; See the OBJECT CODE overview below for details on the object format.
;*******************************************************************************

.include "asm.inc"
.include "config.inc"
.include "debuginfo.inc"
.include "errors.inc"
.include "file.inc"
.include "kernal.inc"
.include "labels.inc"
.include "limits.inc"
.include "line.inc"
.include "log.inc"
.include "macros.inc"
.include "math.inc"
.include "memory.inc"
.include "object.inc"
.include "string.inc"
.include "strings.inc"
.include "util.inc"
.include "target.inc"
.include "text.inc"
.include "vmem.inc"
.include "zeropage.inc"

.include "ram.inc"

.macpack longbranch

.import __LINKER_BSS_LOAD__
.import __LINKER_BSS_SIZE__

;*******************************************************************************
; CONSTANTS
MAX_SECTIONS         = 8	; max number of memory sections
MAX_SECTION_NAME_LEN = 8	; max length of a single section name
MAX_SEGMENT_NAME_LEN = 8	; max length of a single segment name

MAX_SYMBOL_NAME_LEN = 32
MAX_SYMBOLS         = 128	; max # of symbols per object file

SYM_IMPORT_BYTE     = 1
SYM_IMPORT_WORD     = 2
SYM_REL_EXPORT_BYTE = 3
SYM_REL_EXPORT_WORD = 4
SYM_ABS_EXPORT_BYTE = 5
SYM_ABS_EXPORT_WORD = 6

;*******************************************************************************
; SECTION flags
SECTION_FILL = $01	; flag to pad section's unused bytes with 0

; LINK definition properties seen while parsing
SECTION_PROP_START     = $01
SECTION_PROP_END       = $02
SECTION_PROPS_REQUIRED = SECTION_PROP_START | SECTION_PROP_END

SEGMENT_PROP_LOAD      = $01
SEGMENT_PROP_RUN       = $02
SEGMENT_PROPS_REQUIRED = SEGMENT_PROP_LOAD

;*******************************************************************************
; ZEROPAGE variables
; OBJPTR is the cursor in the object code (where we are reading in the current
; object file)
; SEGPTR is the cursor to the .PRG or .D file (where we are WRITIING)
objptr=zp::link
segptr=zp::link+2

;*******************************************************************************
; OBJFILES
; The list of object files to link
; Represented as a 0-terminated list of 0-terminated filename
; e.g.
;   "FILE1.O",0,"FILE2.O",0,0

.export __link_objfiles
__link_objfiles=mem::spare

;*******************************************************************************
.segment "LINKER_VARS"

numsegments: .byte 0
numsections: .byte 0

activeobj:         .byte 0	; the current OBJECT (id) being linked
objerr:            .byte 0	; error code from linking an object
parsed_properties: .byte 0	; properties seen in the current LINK definition
absolute_end:      .word 0	; next free entry in absolute_ranges
linkpass:          .byte 0	; 1 while pass 1 is running, 2 during pass 2

;*******************************************************************************
; OBJECT STATE
; These variables are used in the context of a single object file
numsymbols:  .byte 0

.segment "LINKER_BSS"

; Fragments are collected in object/header order before layout.  Their IDs
; temporarily occupy labels' segment fields until resolve_symbols runs.
num_fragments: .res 1
object_fragbase: .res MAX_OBJS
fragment_segment: .res MAX_LINK_FRAGMENTS
fragment_sizelo: .res MAX_LINK_FRAGMENTS
fragment_sizehi: .res MAX_LINK_FRAGMENTS
fragment_alignlo: .res MAX_LINK_FRAGMENTS
fragment_alignhi: .res MAX_LINK_FRAGMENTS
fragment_fill: .res MAX_LINK_FRAGMENTS
fragment_padlo: .res MAX_LINK_FRAGMENTS
fragment_padhi: .res MAX_LINK_FRAGMENTS
.export __link_fragment_loadlo, __link_fragment_loadhi
.export __link_fragment_runlo, __link_fragment_runhi
__link_fragment_loadlo: .res MAX_LINK_FRAGMENTS
__link_fragment_loadhi: .res MAX_LINK_FRAGMENTS
__link_fragment_runlo: .res MAX_LINK_FRAGMENTS
__link_fragment_runhi: .res MAX_LINK_FRAGMENTS

;*******************************************************************************
; SECTIONS
; The memory section contains up to MAX_SECTIONS of memory blocks.  Each
; defines the start and end addresses of the section plus a byte of flag
; data, which is used to, for example, flag that the section should be padded
; if the SEGMENTs that map to this section do not span the entire
; [start, stop) address space.
; The format of a SECTION is:
;  .word start addr
;  .word stop addr
;  .byte flags
sections_startlo: .res MAX_SECTIONS
sections_starthi: .res MAX_SECTIONS
sections_stoplo:  .res MAX_SECTIONS
sections_stophi:  .res MAX_SECTIONS
sections_flags:   .res MAX_SECTIONS
section_names:    .res MAX_SECTIONS*MAX_SECTION_NAME_LEN

.export sections_startlo
.export sections_starthi
.export sections_stoplo
.export sections_stophi
.export sections_flags
.export section_names

;*******************************************************************************
; SEGMENTS
; Segments define where the code or data that occupies them will be mapped to
; the memory defined in the SECTIONS blocks
; SEGMENTs may LOAD to one address but RUN in another. Note the corresponding
; bytes in the SEGMENT structure that select this.
;
; SEGMENTs have the format:
;  .byte[8] name
;  .byte    LOAD SEGMENT id
;  .byte    RUN SEGMENT id
;  .byte    flags
segments_load:   .res MAX_SEGMENTS	; id of SECTION to load to
segments_run:    .res MAX_SEGMENTS	; id of SECTION to run at
segments_flags:  .res MAX_SEGMENTS
segments_sizelo: .res MAX_SEGMENTS
segments_sizehi: .res MAX_SEGMENTS
segments_type:   .res MAX_SEGMENTS

; The alignment required of each SEGMENT: the LINK file's ALIGN property
; combined (see lcm16) with the alignment every object file asks of the SEGMENT
; through its .ALIGN directives.  0 or 1 means the SEGMENT is unaligned.
; Alignments need not be powers of 2, so rounding goes through align_up.
segments_alignlo: .res MAX_SEGMENTS
segments_alignhi: .res MAX_SEGMENTS

; pointers for the current LOAD address of each SEGMENT during linking.
; This is where the SEGMENT's bytes are placed in the output image.
segments_addrlo: .res MAX_SEGMENTS
segments_addrhi: .res MAX_SEGMENTS

; pointers for the current RUN address of each SEGMENT during linking.
; This is the address the SEGMENT's code is relocated for; it differs from the
; LOAD address when the SEGMENT declares a RUN SECTION of its own (the program
; is expected to copy the SEGMENT from LOAD to RUN before executing it).
segments_runaddrlo: .res MAX_SEGMENTS
segments_runaddrhi: .res MAX_SEGMENTS

segment_names: .res MAX_SEGMENT_NAME_LEN*MAX_SEGMENTS

; Absolute SEGMENT ranges collected from object headers.  Each record is
; start, stop (two little-endian words).  The maximum follows from the object
; and per-object SEGMENT limits.
absolute_ranges: .res MAX_OBJS*MAX_SEGMENTS*4
absolute_ranges_end = *

.export segments_load
.export segments_run
.export segments_flags
.export segments_sizelo
.export segments_sizehi
.export segments_alignlo
.export segments_alignhi
.export segment_names

;*******************************************************************************
; OBJECT CODE overview
; See object.asm for the byte-level format. Headers describe ordered
; object-local fragments of named SEGMENTs, followed by symbols, code,
; relocation tables and debugger line programs.
;
; Pass 1 collects fragment sizes and alignment constraints. Layout assigns
; each fragment fixed LOAD/RUN bases, including padding, then resolves symbols
; as fragment RUN base + offset. Pass 2 emits padding/code and relocates each
; operand at its containing fragment's fixed address. Neither symbols nor
; branches assume that offsets in different fragments share a displacement.
;*******************************************************************************

;*******************************************************************************
; DEBUG FILE overview
; Debug (.d) files are binary files that contain the linked object code.
; They are similar to the object files that they are built from.
;
; Debug files cannot be run outside the Monster environment. To produce a
; standalone .PRG use dbg::linkprg
;
; EXAMPLE:
;  FILE NAMES:
;   hello.s
;   main.s
;
;  NUM_SYMBOLS: 4
;
;  SYMBOLS:
;   LAB1     CODE+$1600  hello.s L:120
;   LAB2     CODE+$1402  hello.s L:40
;   my_proc  CODE+$1000  main.s  L:200
;   my_proc2 SETUP+$20   main.s  L:10
;
;  SEGMENTS:
;   CODE $1032
;   DATA $062
;*******************************************************************************

;*******************************************************************************
; OBJ Code Opcodes
; These represent the "instruction" opcodes of the object code
OBJ_SETSEG  = $01       ; switches to the given segment e.g. "SEG DATA"
OBJ_BYTES   = $02 	; RLE encoded byte values e.g. "B 4 0 1 2 3"
OBJ_RELBYTE = $03	; byte value + word offset "RB LAB+3"
OBJ_RELWORD = $04	; word value + word offset "RW LAB+10"
OBJ_RELZP   = $05	; byte value followed by relative byte "RZ $20 LAB+10"
OBJ_RELABS  = $06	; byte value followed by relative word "RA $20 LAB+5"

BANKED_SEG "LINKER", FINAL_BANK_LINKER

;*******************************************************************************
; INIT
; Initializes the linker state
.export __link_init
.proc __link_init
@bss=r0
	; clear the LINKER_BSS segment
	ldxy #__LINKER_BSS_LOAD__
	stxy @bss

	lda #$00
@l0:	ldy #$00
	tya
	sta (@bss),y
	incw @bss
	ldxy @bss
	cmpw #__LINKER_BSS_LOAD__+__LINKER_BSS_SIZE__
	bne @l0

	lda #$00
	sta numsegments
	sta numsections
	lda #$01
	sta activeobj
	sta linkpass
	ldxy #absolute_ranges
	stxy absolute_end

	rts
.endproc

;*******************************************************************************
; PARSE LINK FILE
; Parses the given linker config file into sections and segments, loading
; those into the linker's own section and segment state.
; The file must follow the format:
;
; ```
; MEMORY [
; SECTIONA:
;  start=$0000
;  end=$1000
; SECTIONB:
;  ...
; ]
; SEGMENTS [
;  SEGA: load = SECTIONA
;  run = SECTIONB
; ]
; ```
;
; IN:
;  - .XY: pointer to the link filename
;  - .A:  length of the filename
; OUT:
;  - .C: set if the file could not be successfully opened or parsed
.export __link_parse
.proc __link_parse
@filebuff=mem::spare
@filebuff_end=mem::spareend
@segments_declared=r8
@sections_declared=r9
@buff=ra
@errcode=r0
	; set default TYPE attribute (all segments as UNDEF)
	ldy #MAX_SEGMENTS
	lda #TYPE_UNDEF
:	sta segments_type-1,y
	dey
	bne :-

	; load link file into filebuff
	ldxy #strings::link
	CALLMAIN file::open_r
	bcc :+
	rts					; failed to open the link file
:	pha					; save file ID
	tax
	jsr krn::chkin

	; read the file into the buffer (until EOF)
	ldxy #@filebuff
	stxy @buff
@readfile:
	ldxy @buff
	cmpw #@filebuff_end		; is the buffer full?
	bcs @toobig
	jsr krn::chrin
	ldy #$00
	jsr capitalize			; uppercase the input
	sta (@buff),y
	incw @buff
	jsr krn::readst
	cmp #$00
	beq @readfile

	; read done; map KERNAL status to an internal error code
	cmp #$40			; EOF is the only clean way to finish
	beq @readok
	lda #ERR_IO_ERROR		; any other status is a read failure
	bne @closefile			; branch always

@toobig:
	lda #ERR_FILE_TOO_BIG
	skw
@readok:
	lda #$00
;-------------------------------------------------------------------------------
@closefile:
	sta @errcode
	pla				; restore file ID
	CALLMAIN file::close		; CLOSE the LINK file

	lda @errcode
	beq @parse			; no read error -> parse the buffer
	sec
	rts				; return read error

@parse:
	ldxy #@filebuff
	stxy zp::line

	lda #$00
	sta @sections_declared
	sta @segments_declared

@getblock:
	; have all required blocks been declared?
	lda @sections_declared
	and @segments_declared
	beq @read_block

	; done, make sure rest of file is whitespace
:	ldy #$00
	lda (zp::line),y
	jsr is_ws
	bne @unexpected_char
	incw zp::line
	ldxy zp::line
	cmpw @buff
	bne :-
@done:	RETURN_OK

;-------------------------------------------------------------------------------
@read_block:
	; look for MEMORY or SEGMENTS definition
	jsr process_ws
	ldy #$00

	; is line "MEMORY"?
	ldxy #@memory
	jsr cmpline
	beq @parse_sections

	; else is line "SEGMENTS"?
	ldxy #@segments
	jsr cmpline
	beq @parse_segments

	; else invalid string
	RETURN_ERR ERR_SYNTAX_ERROR	; not a MEMORY or SEGMENTS block

@err:	rts			; propagate the error code already in .A

@too_many:
	RETURN_ERR ERR_TOO_MANY_SEGMENTS

;-------------------------------------------------------------------------------
@parse_sections:
	; make sure we haven't already declared sections
	lda @sections_declared
	beq :+
	RETURN_ERR ERR_DUPLICATE_BLOCK	; MEMORY block already declared

:	; read past "MEMORY" declaration
	CALLMAIN line::process_word
	inc @sections_declared

	; look for the '['
	jsr @get_open_brace
	beq :+
@unexpected_char:
	RETURN_ERR ERR_UNEXPECTED_CHAR

	; read the section into the section definitions table
:	incw zp::line		; move beyond the '['
	jsr process_ws
@l0:	lda numsections
	cmp #MAX_SECTIONS	; is there room for another SECTION?
	bcs @too_many
	jsr parse_section
	bcs @err		; -> rts
	inc numsections		; SECTION was successfully parsed

	jsr @get_closing_brace
	bne @l0			; if not ']', read next section
	incw zp::line		; else, move over the ']'
	jmp @getblock		; and get the next block (SEGMENTS)

;-------------------------------------------------------------------------------
@parse_segments:
	; make sure SEGMENTS weren't already declared
	lda @segments_declared
	beq :+
	RETURN_ERR ERR_DUPLICATE_BLOCK	; SEGMENTS block already declared

:	; read past "SEGMENTS"
	CALLMAIN line::process_word
	inc @segments_declared

	; look for the '['
	jsr @get_open_brace
	beq :+
	RETURN_ERR ERR_UNEXPECTED_CHAR

	; read the section into the section definitions table
:	incw zp::line		; move beyond the '['
	jsr process_ws
@l1:	lda numsegments
	cmp #MAX_SEGMENTS	; is there room for another SEGMENT?
	bcs @too_many
	jsr parse_segment
	bcs @err		; -> rts
	inc numsegments		; SEGMENT was successfully parsed
	jsr @get_closing_brace
	bne @l1			; if not ']', read next segment
	incw zp::line		; else, move over the ']'
	jmp @getblock		; and get next block (SECTIONS)

;-------------------------------------------------------------------------------
; return .Z set if first non-whitespace char is a '['
@get_open_brace:
	jsr process_ws
	ldy #$00
	lda (zp::line),y
	cmp #'['
	rts

;-------------------------------------------------------------------------------
; return .Z set if first non-whitespace char is a ']'
@get_closing_brace:
	jsr process_ws
	ldy #$00
	lda (zp::line),y
	cmp #']'
	rts

;-------------------------------------------------------------------------------
@memory:   .byte "memory",0
@segments: .byte "segments",0
.endproc

;*******************************************************************************
; PARSE SECTION
; Parses the definition for one SECTION in the MEMORY block of the linker file
; A section is defined by the section name followed by a ':'
; Followed by lines defining its start and end address
;
; SECTIONA:
;  start=$0000
;  end=$1000
;  fill=1
;
; IN:
;  - zp::line: points to the buffer to parse the SECTION from
; OUT:
;  - .C: set if section could not be parsed
.proc parse_section
@name=r0
@val=r2
@cnt=r4
@keybuff=$100
	lda #$00
	sta parsed_properties

	; get address to store new section name to
	lda numsections
	asl			; *2
	asl			; *4
	asl			; *8
	adc #<section_names
	sta @name
	lda #>section_names
	adc #$00
	sta @name+1

	; read the section name (string terminated by ':')
	jsr process_ws
	ldy #$00
@l0:	lda (zp::line),y
	bne :+
@err:   RETURN_ERR ERR_UNEXPECTED_CHAR	; line ended without ':'
:	jsr is_newl
	beq @err
	cmp #':'
	beq @cont			; found end of section name
	sta (@name),y
	iny
	cpy #$08
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG	; section name > 8 chars

@cont:	tya
	;sec			; +1 (move pointer after the ':')
	adc zp::line
	sta zp::line
	bcc @check_duplicate
	inc zp::line+1

@check_duplicate:
	; numsections does not include the section currently being parsed
	lda numsections
	beq @getprops
	ldxy @name
	jsr get_section_by_name
	bcs @getprops
	RETURN_ERR ERR_DUPLICATE_NAME

; read all properties defined for the SECTION
@getprops:
	jsr process_ws		; move the key name in section

	ldy #$00
	lda (zp::line),y
	cmp #';'		; are we at the end of the section?
	bne :+

	; make sure section declared all required properties
	lda parsed_properties
	and #SECTION_PROPS_REQUIRED
	cmp #SECTION_PROPS_REQUIRED
	beq @properties_ok
	RETURN_ERR ERR_MISSING_REQUIRED_KEY

@properties_ok:
	incw zp::line		; move beyond the semicolon
	RETURN_OK		; we're at the end, return

:	; read the key of the k/v pair into keybuffer
	ldxy #@keybuff
	jsr readkey
	bcs @err

@keyfound:
	ldxy #@keybuff
	stxy zp::str0

	; find the key that corresponds to the one in the config file
	ldxy #@keys
	stxy zp::str2

	lda #$00
	sta @cnt
@findkey:
	jsr strcmp
	bne @next

@found: ; found the key, run the command to map it
	ldx @cnt
	lda @cmdslo,x
	sta zp::jmpvec
	lda @cmdshi,x
	sta zp::jmpvec+1

	; evaluate the value for the handler
	jsr parse_val
	bcs @ret	; error -> rts

	; run the handler for the given key
	jsr zp::jmpaddr
	bcc @getprops	; repeat (get next key if there is one)
	jcs log_error	; handler failed -> return its error

@next:	; move zp::str2 to the next key to check
	ldy #$00
:	lda (zp::str2),y
	incw zp::str2
	cmp #$00
	bne :-

	; are we out of keys?
	inc @cnt
	lda @cnt
	cmp #@numkeys
	bne @findkey
	RETURN_ERR ERR_UNKNOWN_KEY	; no key matched the one in the file

@ret:	rts

;-------------------------------------------------------------------------------
; handler for the "start" key in config file
@startvec:
	; set the start address for the segment
	txa
	ldx numsections
	sta sections_startlo,x
	tya
	sta sections_starthi,x
	lda parsed_properties
	ora #SECTION_PROP_START
	sta parsed_properties
	rts

;-------------------------------------------------------------------------------
; handler for the "stop" key in config file
@endvec:
	; set the end address for the segment
	txa
	ldx numsections
	sta sections_stoplo,x
	tya
	sta sections_stophi,x
	lda parsed_properties
	ora #SECTION_PROP_END
	sta parsed_properties
	rts

;-------------------------------------------------------------------------------
; handler for the "fill" key in config file
@fillvec:
	cpy #$00
	bne @fill_enable
	cpx #$00
	bne @fill_enable

@fill_disable:
	ldx numsections
	lda sections_flags,x
	and #($ff ^ SECTION_FILL)
	sta sections_flags,x
	RETURN_OK

@fill_enable:
	ldx numsections
	lda sections_flags,x
	ora #SECTION_FILL
	sta sections_flags,x
	RETURN_OK

;-------------------------------------------------------------------------------
; keys table
@keys:
@numkeys=3
@start:	.byte "start",0
@end:	.byte "end",0
@fill:	.byte "fill",0

;-------------------------------------------------------------------------------
; keys table handler vectors
.define sec_cmds @startvec, @endvec, @fillvec
@cmdslo: .lobytes sec_cmds
@cmdshi: .hibytes sec_cmds

.endproc

;*******************************************************************************
; PARSE SEGMENT
; Parses the definition for one SEGMENT in the SEGMENTS block of the linker file
; A segment is defined by the section name followed by a ':'
; Followed by lines defining its load and run addresses
; SEGA:
;  load=$0000
;  run=$1000
; IN:
;  - zp::line: points to the buffer to parse the SEGMENT from
; OUT:
;  - .C: set if the segment could not be parsed
.proc parse_segment
@name=r0
@val=r2
@cnt=r4
@alignval=r6
@keybuff=$100
@valbuff=$100
	lda #$00
	sta parsed_properties

	; get address to store new segment name to
	lda #$00
	sta @name+1
	lda numsegments
	asl			; *2
	rol @name+1
	asl			; *4
	rol @name+1
	asl			; *8
	rol @name+1
	adc #<segment_names
	sta @name
	lda @name+1
	adc #>segment_names
	sta @name+1

	; read the segment name (string terminated by ':')
	jsr process_ws
	ldy #$00
@l0:	lda (zp::line),y
	bne :+
@err:   RETURN_ERR ERR_UNEXPECTED_CHAR	; line ended without ':'
:	jsr is_newl
	beq @err
	cmp #':'
	beq @cont			; found end of section name
	sta (@name),y
	iny
	cpy #MAX_SEGMENT_NAME_LEN
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG	; section name > 8 chars

@cont:	tya
	;sec			; +1 (move pointer after the ':')
	adc zp::line
	sta zp::line
	bcc @check_duplicate
	inc zp::line+1

@check_duplicate:
	; numsegments does not include the segment currently being parsed
	lda numsegments
	beq @getprops
	ldxy @name
	jsr get_segment_by_name
	bcs @getprops
	RETURN_ERR ERR_DUPLICATE_NAME

; read all properties defined for the SEGMENT
@getprops:
	jsr process_ws		; move the key name in segment

	ldy #$00
	lda (zp::line),y
	cmp #';'		; are we at the end of the segment?
	bne :+
	lda parsed_properties
	and #SEGMENT_PROPS_REQUIRED
	cmp #SEGMENT_PROPS_REQUIRED
	beq @properties_ok
	RETURN_ERR ERR_MISSING_REQUIRED_KEY

@properties_ok:
	; RUN defaults to LOAD when omitted
	lda parsed_properties
	and #SEGMENT_PROP_RUN
	bne @properties_done
	ldx numsegments
	lda segments_load,x
	sta segments_run,x

@properties_done:
	incw zp::line		; move beyond the semicolon
	RETURN_OK		; we're at the end, return

:	; read the key of the k/v pair into keybuffer
	ldxy #@keybuff
	jsr readkey
	bcs @err

@keyfound:
	ldxy #@keybuff
	stxy zp::str0

	; find the key that corresponds to the one in the config file
	ldxy #@keys
	stxy zp::str2

	lda #$00
	sta @cnt
@findkey:
	jsr strcmp
	bne @next

@found: ; found the key, run the command to map it
	ldx @cnt
	lda @cmdslo,x
	sta zp::jmpvec
	lda @cmdshi,x
	sta zp::jmpvec+1

	; read the value that the key is assigned into a temp buffer
	ldy #$00
:	lda (zp::line),y
	beq @get_section
	cmp #';'
	beq @get_section
	jsr is_ws
	beq @get_section
	sta @valbuff,y
	iny
	bne :-

@get_section:
	lda #$00
	sta @valbuff,y	; terminate the section name buffer

	; update line pointer to after the name that was read
	tya
	clc
	adc zp::line
	sta zp::line
	bcc :+
	inc zp::line+1

:	; run the handler for the given key
	jsr zp::jmpaddr
	jcc @getprops		; repeat (get next key if there is one)
	jcs log_error

@next:	; move zp::str2 to the next key to check
	ldy #$00
:	lda (zp::str2),y
	incw zp::str2
	cmp #$00
	bne :-

	; are we out of keys?
	inc @cnt
	lda @cnt
	cmp #@numkeys
	bne @findkey
	RETURN_ERR ERR_UNKNOWN_KEY	; no key matched the one in the file

;-------------------------------------------------------------------------------
; handler for the "run" key in SEGMENT
@runvec:
	; get the section ID
	ldxy #@valbuff
	jsr get_section_by_name
	bcc :+
	lda #ERR_UNKNOWN_SEGMENT	; section not found -> rts
	rts

:	; set the run section for the segment
	ldx numsegments
	sta segments_run,x
	lda parsed_properties
	ora #SEGMENT_PROP_RUN
	sta parsed_properties
	RETURN_OK

;-------------------------------------------------------------------------------
; handler for the "load" key in SEGMENT
@loadvec:
	; get the section ID
	ldxy #@valbuff
	jsr get_section_by_name
	bcc :+
	lda #ERR_UNKNOWN_SEGMENT	; section not found -> rts
	rts

:	; set the load section for the segment
	ldx numsegments
	sta segments_load,x
	lda parsed_properties
	ora #SEGMENT_PROP_LOAD
	sta parsed_properties
	RETURN_OK

;-------------------------------------------------------------------------------
; handler for the "align" key in SEGMENT
@alignvec:
	ldxy #@valbuff
	jsr parse_num			; get the requested alignment
	bcs @badalign			; not a number -> error

	stxy @alignval
	lda @alignval
	ora @alignval+1
	beq @badalign			; ALIGN=0 is not an alignment

	; the SEGMENT is aligned to at least this; the .ALIGN directives in the
	; objects that use it may raise it further (see link::require_align)
	ldx numsegments
	lda @alignval
	sta segments_alignlo,x
	lda @alignval+1
	sta segments_alignhi,x
	RETURN_OK

@badalign:
	RETURN_ERR ERR_INVALID_ALIGNMENT

;-------------------------------------------------------------------------------
; keys table
@numkeys=3
@keys:
@load:  .byte "load",0
@run:   .byte "run",0
@align: .byte "align",0

;-------------------------------------------------------------------------------
; keys table handler vectors
.define seg_cmds @loadvec, @runvec, @alignvec
@cmdslo: .lobytes seg_cmds
@cmdshi: .hibytes seg_cmds

.endproc

;*******************************************************************************
; VALIDATE SYMBOLS
; Validates that all symbols are resolved
; OUT:
;   - .C: set on error
.proc validate_symbols
@i=zp::tmp10
@seg_id=zp::tmp12
@obj_seg_offsets=zp::tmp14
@namebuff=$100
	iszero lbl::num
	beq @ok

	; iterate through all labels
	lda #$00
	sta @i
	sta @i+1

@l0:	ldxy @i
	CALLMAIN lbl::getsegment		; get segment ID
	cmp #SEG_UNDEF				; is segment UNDEFINED?
	beq @err				; if so, error
	incw @i
	ldxy @i
	cmpw lbl::num
	bne @l0

@ok:	RETURN_OK
@err:	RETURN_ERR ERR_LABEL_UNDEFINED
.endproc

;*******************************************************************************
; RESOLVE SYMBOLS
; Finalizes the values of the relocatable symbols registered during pass 1 by
; adding the (now known) origin of their SEGMENT to their segment-relative
; values.
; ABS symbols and (still) UNDEFINED symbols are unaffected.
; This must be called after calc_seg_origins and before pass 2.
.proc resolve_symbols
@i=zp::tmp10
@seg=zp::tmp12
@mode=zp::tmp13
	iszero lbl::num
	beq @done

	lda #$00
	sta @i
	sta @i+1

@l0:	ldxy @i
	CALLMAIN lbl::getsegment	; get the label's segment ID
	cmp #SEG_UNDEF			; undefined? (import nobody exported)
	beq @next			; leave it (caught by validation later)
	cmp #SEG_ABS			; absolute?
	beq @next			; if so, the value is already final
	cmp #SEG_FLOAT
	beq @next			; numeric value, not a segment-relative address
	sta @seg

	ldxy @i
	CALLMAIN lbl::addrmode		; get the address mode
	sta @mode			; (keep it unchanged)

	ldxy @i
	CALLMAIN lbl::getaddr		; .XY = segment-relative value

	; value = segment RUN origin + segment-relative value
	; (symbols name the address the code will execute at, not where it loads)
	txa
	ldx @seg
	clc
	adc __link_fragment_runlo-1,x
	sta zp::label_value
	tya
	adc __link_fragment_runhi-1,x
	sta zp::label_value+1
	ldx @seg
	lda fragment_segment-1,x
	sta zp::label_segmentid
	lda @mode
	sta zp::label_mode

	ldxy @i
	CALLMAIN lbl::setaddr		; write back the finalized value

@next:	incw @i
	ldxy @i
	cmpw lbl::num
	bne @l0

@done:	RETURN_OK
.endproc

;*******************************************************************************
; CALC SEG ORIGINS
; Calculates the LOAD and RUN start addresses for each global SEGMENT.
; SEGMENTs are packed into their SECTION in LINK-file order.  The LOAD and RUN
; layouts are packed independently: a SEGMENT occupies space in the SECTION it
; LOADs to (where its bytes go in the output image) and, separately, in the
; SECTION it RUNs in (the address its code is relocated for).  For the common
; case where RUN and LOAD name the same SECTION the two layouts are identical.
; OUT:
;   - .C: set on error
.proc calc_seg_origins
@fill_start = r2
@cursorlo = zp::asmtmp
@cursorhi = @cursorlo+MAX_SECTIONS
@value   = r0
@padding = r4
@load    = r6
@run     = r8
@seg     = ra
@frag    = rb
@fill    = rd
	ldx numsections
	jeq @ok

@init:	dex
	lda sections_startlo,x
	sta @cursorlo,x
	lda sections_starthi,x
	sta @cursorhi,x
	cpx #$00
	bne @init
	stx @seg

;-------------------------------------------------------------------------------
; set LOAD and RUN addresses for SEGMENT by looking up current cursor values
@segment:
	ldx @seg
	cpx numsegments
	jcs @validate
	ldy segments_run,x
	lda @cursorlo,y
	sta @run
	lda @cursorhi,y
	sta @run+1
	ldy segments_load,x
	lda @cursorlo,y
	sta @load
	lda @cursorhi,y
	sta @load+1

;-------------------------------------------------------------------------------
; apply ALIGNment for the segment (if it has any)
	lda segments_alignlo,x
	sta m::arg
	lda segments_alignhi,x
	sta m::arg+1
	ldxy @run
	CALL FINAL_BANK_EXPR, m::align_up
	jcs @overflow
	stxy @run
	ldxy @load
	CALL FINAL_BANK_EXPR, m::align_up
	jcs @overflow
	stxy @value			; set stop address for fill
	lda #$00
	sta @fill			; init fill value to 0
	ldx @seg
	lda segments_type,x
	cmp #TYPE_SEGZP
	beq @setbase			; don't fill ZP segments
	cmp #TYPE_BSSZP
	beq @setbase			; don't fill BSS segments
	ldxy @load
	stxy @fill_start
	jsr fill_span			; fill from [@fill_start, @value)

;-------------------------------------------------------------------------------
@setbase:
	ldxy @value
	stxy @load
	ldx @seg
	lda @load
	sta segments_addrlo,x
	lda @load+1
	sta segments_addrhi,x
	lda @run
	sta segments_runaddrlo,x
	lda @run+1
	sta segments_runaddrhi,x
	lda #$00
	sta @frag

;-------------------------------------------------------------------------------
@fragment:
	ldx @frag
	cpx num_fragments
	jcs @finish
	lda fragment_segment,x
	sec
	sbc #$01
	cmp @seg
	jne @next

	; apply fragment-level alignment (.align directives in the obj code)
	lda fragment_alignlo,x
	sta m::arg
	lda fragment_alignhi,x
	sta m::arg+1
	ldxy @run
	CALL FINAL_BANK_EXPR, m::align_up
	jcs @overflow
	stxy @value
	txa
	sec
	sbc @run
	sta @padding

	tya
	sbc @run+1
	sta @padding+1
	ldxy @value
	stxy @run
	lda @load
	clc
	adc @padding
	sta @load

	lda @load+1
	adc @padding+1
	sta @load+1
	jcs @overflow
	ldx @frag
	lda @padding
	sta fragment_padlo,x
	lda @padding+1
	sta fragment_padhi,x

	lda @load
	sta __link_fragment_loadlo,x
	lda @load+1
	sta __link_fragment_loadhi,x
	lda @run
	sta __link_fragment_runlo,x
	lda @run+1
	sta __link_fragment_runhi,x

	lda fragment_sizelo,x
	sta @value
	lda fragment_sizehi,x
	sta @value+1

	jsr advance_layout
	jcs @overflow

@next:	inc @frag
	jmp @fragment

;-------------------------------------------------------------------------------
@finish:
	ldx @seg
	lda @run
	sec
	sbc segments_runaddrlo,x
	sta segments_sizelo,x
	lda @run+1
	sbc segments_runaddrhi,x
	sta segments_sizehi,x
	ldy segments_load,x
	lda @load
	sta @cursorlo,y
	lda @load+1
	sta @cursorhi,y
	ldy segments_run,x
	lda @run
	sta @cursorlo,y
	lda @run+1
	sta @cursorhi,y
	inc @seg
	jmp @segment

;-------------------------------------------------------------------------------
@validate:
	ldx #$00
@check:	cpx numsections
	beq @ok
	lda sections_stoplo,x
	cmp @cursorlo,x
	lda sections_stophi,x
	sbc @cursorhi,x
	bcc @small
	inx
	bne @check
@ok:	RETURN_OK
@small:	RETURN_ERR ERR_SECTION_TOO_SMALL
@overflow:
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc

;*******************************************************************************
; ADVANCE LAYOUT
; Adds the given value to the LOAD and RUN cursors.
; IN:
;   - r0/r1: the amount to add to LOAD and RUN cursors
.proc advance_layout
@size = r0
@load = r6
@run  = r8
	lda @load
	clc
	adc @size
	sta @load
	lda @load+1
	adc @size+1
	sta @load+1
	bcs @ret
	lda @run
	clc
	adc @size
	sta @run
	lda @run+1
	adc @size+1
	sta @run+1
@ret:	rts
.endproc

;*******************************************************************************
; FILL SPAN
; Fill [r2, r0) with rd, preserving absolute objects
.proc fill_span
@stop   = r0
@cursor = r2
@fill   = rd

@loop:	lda @cursor
	cmp @stop
	lda @cursor+1
	sbc @stop+1
	bcs @done
	jsr skip_absolute
	bcs @loop
	lda @fill
	ldxy @cursor
	CALLMAIN vmem::store
	incw @cursor
	jmp @loop

@done:	rts
.endproc

;*******************************************************************************
; FRAGMENT
; Looks up the global FRAGMENT ID for the given local FRAGMENT
; IN:
;   - .A = named segment ($ff for ABS)
;   - .X = object-local fragment index.
; OUT:
;   - .A: global fragment ID
.pushseg
; The linker ROM bank cannot hold this helper as well. Keep only this
; registration/lookup routine resident; callers still select the linker bank
; for its tables.
.segment "DATA"
.export __link_fragment
.proc __link_fragment
@parent = re
@local  = rf
	sta @parent
	stx @local
	lda linkpass
	cmp #$02
	beq @lookup
	cpx #$00
	bne @append
	ldy activeobj
	lda num_fragments
	sta object_fragbase-1,y

@append:
	ldy num_fragments
	cpy #MAX_LINK_FRAGMENTS
	bcs @full
	lda @parent
	sta fragment_segment,y
	lda obj::segments_sizelo,x
	sta fragment_sizelo,y
	lda obj::segments_sizehi,x
	sta fragment_sizehi,y
	lda obj::alignlo,x
	sta fragment_alignlo,y
	lda obj::alignhi,x
	sta fragment_alignhi,y
	lda obj::fill,x
	sta fragment_fill,y
	lda #$00
	sta fragment_padlo,y
	sta fragment_padhi,y
	sta __link_fragment_loadlo,y
	sta __link_fragment_loadhi,y
	sta __link_fragment_runlo,y
	sta __link_fragment_runhi,y
	lda @parent
	cmp #SEG_ABS
	bne @added
	lda obj::segments_startlo,x
	sta __link_fragment_loadlo,y
	sta __link_fragment_runlo,y
	lda obj::segments_starthi,x
	sta __link_fragment_loadhi,y
	sta __link_fragment_runhi,y
@added:	inc num_fragments
	lda num_fragments
	clc
	rts
@lookup:
	ldy activeobj
	lda object_fragbase-1,y
	clc
	adc @local
	cmp num_fragments
	bcs @full
	tay
	lda fragment_segment,y
	cmp @parent
	bne @full
	tya
	clc
	adc #$01
	clc
	rts
@full:	RETURN_ERR ERR_TOO_MANY_SEGMENTS
.endproc
.popseg

;*******************************************************************************
; PAD FRAGMENT
; Write the alignment bytes immediately preceding the given global fragment
.export __link_pad_fragment
.proc __link_pad_fragment
@start = r2
@stop = r0
@fill = rd
	tax
	lda fragment_segment-1,x
	cmp #SEG_ABS
	beq @done
	tay

	lda segments_type-1,y
	cmp #TYPE_SEGZP
	beq @done
	cmp #TYPE_BSSZP
	beq @done

	lda __link_fragment_loadlo-1,x
	sta @stop
	sec
	sbc fragment_padlo-1,x
	sta @start
	lda __link_fragment_loadhi-1,x
	sta @stop+1
	sbc fragment_padhi-1,x
	sta @start+1
	lda fragment_fill-1,x
	sta @fill
	jsr fill_span

@done:	rts
.endproc

;*******************************************************************************
; FILL SECTIONS
; 0 pads the unused bytes of each SECTION configured with FILL=true
; The SECTION is scanned from START to END and every byte that no SEGMENT wrote
; to is zeroed.  The bytes in a SECTION are not necessarily contiguous from
; "START". A SEGMENT that only RUNs in the SECTION reserves address space but
; writes nothing there (see calc_seg_origins), and that gap is unused memory
; like any other, so FILL zeroes it.
.proc fill_sections
@section=r0
@addr=r2
	lda numsections
	jeq @done

	lda #$00
	sta @section

@section_loop:
	ldx @section
	lda sections_flags,x
	and #SECTION_FILL
	jeq @next_section

	; a zeropage SECTION holds no bytes of the image -> skip
	lda @section
	jsr is_zp_section
	jeq @next_section
	ldx @section			; restore the SECTION index

	; an empty SECTION contributes no bytes to the output
	lda sections_startlo,x
	cmp sections_stoplo,x
	bne @nonempty_section
	lda sections_starthi,x
	cmp sections_stophi,x
	jeq @next_section

@nonempty_section:
	; begin the scan at the SECTION's START
	lda sections_startlo,x
	sta @addr
	lda sections_starthi,x
	sta @addr+1

	; include the entire filled SECTION in the flat output
	ldx @section
	lda sections_starthi,x
	cmp asm::origin+1
	bcc @set_origin
	bne @check_top
	lda sections_startlo,x
	cmp asm::origin
	bcs @check_top

@set_origin:
	lda sections_startlo,x
	sta asm::origin
	lda sections_starthi,x
	sta asm::origin+1

@check_top:
	lda sections_stophi,x
	cmp asm::top+1
	bcc @fill
	bne @set_top
	lda sections_stoplo,x
	cmp asm::top
	bcc @fill
	beq @fill

@set_top:
	lda sections_stoplo,x
	sta asm::top
	lda sections_stophi,x
	sta asm::top+1

@fill:	; stop when fill pointer reaches the SECTION's END
	ldx @section
	lda @addr
	cmp sections_stoplo,x
	lda @addr+1
	sbc sections_stophi,x
	bcs @next_section	; addr >= END -> SECTION is done

	; ABS SEGMENTs write their own bytes here; don't zero over them
	jsr skip_absolute
	bcs @fill		; addr was advanced -> recheck the SECTION's END

	; SEGMENTs that LOAD here wrote their bytes; don't zero over them
	jsr skip_loaded
	bcs @fill		; addr was advanced -> recheck the SECTION's END

@store_zero:
	lda #$00
	ldxy @addr
	CALLMAIN vmem::store
	incw @addr
	jmp @fill

@next_section:
	inc @section
	lda @section
	cmp numsections
	jcc @section_loop

@done:	rts
.endproc

;*******************************************************************************
; SKIP ABSOLUTE
; Advances the given address past the absolute SEGMENT range that contains it,
; if any.  The ranges are those collected from the object headers during pass 1
; (see add_absolute_segment).
; IN:
;   - r2: the address to check
; OUT:
;   - r2: the address, advanced to the END of the ABS range that contained it
;   - .C: set if the address was advanced
.proc skip_absolute
@addr=r2
@ptr=r4
	ldxy #absolute_ranges
	stxy @ptr

@l0:	ldxy @ptr
	cmpw absolute_end
	beq @done		; end of table -> addr is in no ABS range

	; addr < range.start -> not in this range
	ldy #$00
	lda @addr
	cmp (@ptr),y
	iny
	lda @addr+1
	sbc (@ptr),y
	bcc @next

	; addr >= range.stop -> not in this range
	iny
	lda @addr
	cmp (@ptr),y
	iny
	lda @addr+1
	sbc (@ptr),y
	bcs @next

	; addr is within the range; move it to the range's END
	ldy #$02
	lda (@ptr),y
	sta @addr
	iny
	lda (@ptr),y
	sta @addr+1
	sec			; address was advanced
	rts

@next:	; move to the next 4-byte range record
	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @l0
	inc @ptr+1
	jmp @l0

@done:	clc			; address was not in any ABS range
	rts
.endproc

;*******************************************************************************
; SKIP LOADED
; Advances the given address past the SEGMENT whose bytes occupy it, if any.
; Only the SECTION a SEGMENT LOADs to receives its bytes; the SECTION it RUNs in
; (when that is a different SECTION) holds nothing but a reservation, so a RUN
; range is deliberately not skipped here.
; IN:
;   - r2: the address to check
; OUT:
;   - r2: the address, advanced past the SEGMENT whose bytes contained it
;   - .C: set if the address was advanced
.proc skip_loaded
@addr=r2
@i=r4
@end=r6
	lda #$00
	sta @i
	cmp numsegments
	beq @done		; no SEGMENTs at all -> nothing to skip

@l0:	ldx @i
	; empty SEGMENTs contain no bytes
	lda segments_sizelo,x
	ora segments_sizehi,x
	beq @next		; if empty -> continue to next

	; addr < segment.addr -> not in this SEGMENT
	lda @addr
	cmp segments_addrlo,x
	lda @addr+1
	sbc segments_addrhi,x
	bcc @next

	; end = segment.addr + segment.size
	lda segments_addrlo,x
	clc
	adc segments_sizelo,x
	sta @end
	lda segments_addrhi,x
	adc segments_sizehi,x
	sta @end+1

	; addr >= end -> not in this SEGMENT
	lda @addr
	cmp @end
	lda @addr+1
	sbc @end+1
	bcs @next

	; addr is within the SEGMENT's bytes; move it past them
	ldxy @end
	stxy @addr
	sec			; address was advanced
	rts

@next:	inc @i
	lda @i
	cmp numsegments
	bcc @l0

@done:	clc			; addr is inside no SEGMENT's data -> fill it
	rts
.endproc

;*******************************************************************************
; IS ZP SECTION
; Returns .Z set if any SEGMENT LOADs into the given SECTION as a zeropage
; SEGMENT.
; IN:
;   - .A: the id of the SECTION to test
; OUT:
;   - .Z: set if the SECTION is a zeropage SECTION
.proc is_zp_section
@section=r4
@i=r5
	sta @section
	lda #$00
	sta @i
	cmp numsegments
	beq @no			; no SEGMENTs -> not a zeropage SECTION

@l0:	ldx @i
	lda segments_load,x
	cmp @section
	bne @next		; SEGMENT doesn't load here

	lda segments_type,x
	eor #TYPE_SEGZP
	beq @yes
	lda segments_type,x
	eor #TYPE_BSSZP
	beq @yes

@next:	inc @i
	ldx @i
	cpx numsegments
	bcc @l0

@no:	lda #$01		; .Z clear -> not a zeropage SECTION
	rts

@yes:	lda #$00		; .Z set -> zeropage SECTION
	rts
.endproc

;*******************************************************************************
; LINK
; Links all files that were added to the linker (link::addfile) and produces
; the linked executable as a file with the given name.
; IN:
;  - link::objfiles: array of the files to link (0-terminated)
; OUT:
;  - .C: set on error
.export __link_link
.proc __link_link
@objfile=zp::link+2	; pointer to current object file being linked
@i=zp::link+4
@segname=zp::link+6
@tab=zp::link+8
	; init the segment/section pointers using the current linker state
	; (parsed from the LINK file prior to calling this procedured)
	ldx numsegments
	bne @init
	RETURN_ERR ERR_NO_SEGMENTS	; nothing to link into
@ret:	rts

@init:  ; initialize state:
	; labels (global symbol table)
	; debug info (global debug info)
	CALLMAIN lbl::clr
	CALLMAIN dbgi::init

	jsr init_segments
	lda #$00
	sta num_fragments

	; init obj pointer to start of object list
	ldxy #__link_objfiles
	stxy @objfile

	lda #$01
	sta activeobj
	sta linkpass		; the object headers are read for pass 1

;-------------------------------------------------------------------------------
; PASS1
; Extract header data foreach file and update pointers to each file to the main
; block of the .O file.
; Also define labels for the globals (IMPORT/EXPORT blocks) defined in each
; object file.
	jsr log_banner
	ldxy #strings::pass1
	RENDER_STR
	CALLMAIN log::out
	jsr log_banner

@pass1: ; log the filename being assembled
	ldxy @objfile
	CALLMAIN log::out

	; load the next .O (object) file in the object list
	ldxy @objfile
	stxy obj::filename
	CALLMAIN file::open_r
	jcs log_error			; failed to open object file -> error
	pha				; save file handle
	tax
	jsr krn::chkin			; CHKIN
	jsr obj::load_headers	; get section sizes and add global labels
	sta objerr		; save error code
	pla			; restore file handle
	php			; save .C (error)
	CALLMAIN file::close	; close the object file
	plp			; restore load_headers error
	lda objerr		; restore error code
	jcs log_error

	jsr update_segments
	jcs log_error

@nextfile:
	jsr log_newl

	; next file; update filename pointer to next filename
	ldy #$01		; start search at 2nd character of filename
:	lda (@objfile),y	; get a char
	beq :+			; if 0, we've found terminator -> continue
	iny			; next char
	bne :-			; repeat til we've found 0

:	tya
	clc
	adc @objfile
	sta @objfile
	bcc :+
	inc @objfile+1
:	ldy #$01
	lda (@objfile),y	; get char after the terminating 0
	beq @pass1done		; if it's another 0, we're at end of obj list
	incw @objfile		; move to the next filename

	inc activeobj
	jmp @pass1		; if not, repeat for next obj file
;-------------------------------------------------------------------------------

@pass1done:
	; Layout reuses the now-dead @objfile pointer's scratch window.
	jsr calc_seg_origins
	jcs log_error
	jsr validate_segments
	jcs log_error

	; now that SEGMENT origins are known, finalize the values of the
	; symbols that were registered (segment-relative) during pass 1
	ldxy #@resolving_symbols
	jsr log_msg
	jsr resolve_symbols
	jcs log_error

@start_pass2:
	jsr log_banner
	ldxy #strings::pass2
	RENDER_STR
	CALLMAIN log::out
	jsr log_banner

	; reset obj pointer to start of object list
	ldxy #__link_objfiles
	stxy @objfile
	lda #$01
	sta activeobj
	lda #$02
	sta linkpass		; the headers are read again for pass 2

;-------------------------------------------------------------------------------
; PASS2
; iterate over each object file again, but this time link it to to produce the
; final binary.
@pass2: ldxy @objfile
	CALLMAIN log::out

	ldxy @objfile
	jsr link_object		; link the object file
	bcs log_error		; if .C set, return with error

	jsr log_newl

	; update filename pointer to next filename
	ldy #$0
:	lda (@objfile),y
	beq :+
	iny
	bne :-

:	tya
	clc
	adc @objfile
	sta @objfile
	bcc :+
	inc @objfile+1

:	inc activeobj

	ldy #$01
	lda (@objfile),y	; are we done? (0 at end of file list)
	beq @pass2done
	incw @objfile
	jmp @pass2		; repeat for all object files

;-------------------------------------------------------------------------------
@pass2done:
	; Fragment and segment origins remain fixed throughout pass 2.
	; calculate ORIGIN and TOP of linked program
	jsr segmin
	stxy asm::origin
	jsr segmax
	stxy asm::top
	jsr fill_sections	; fill any sections that are marked "FILL"

	jsr validate_symbols
	jcs log_error

	jsr generate_map	; produce the map file
	jcs log_error
	RETURN_OK

@done:	rts

@resolving_symbols: .byte "resolving symbols",0
.endproc

;*******************************************************************************
; LOG ERROR
; Logs the error given
; IN:
;   - .A: error code to log
.proc log_error
	pha
	CALLMAIN err::get
	CALLMAIN log::out
	pla
	sec
	rts			; return err
.endproc

;*******************************************************************************
; LINK OBJECT
; Produces the final binary for a given object file
; IN:
;   - .XY: address of the object filename to link
.proc link_object
@err=objerr	; NOTE: must survive file::close (which may clobber r0-r15)
	CALLMAIN file::open_r
	bcs @ret		; failed to open the object file -> error

	pha			; save file ID
	tax
	jsr krn::chkin		; CHKIN
	jsr obj::load		; load the object file with the given index

	sta @err
	pla			; restore file ID
	php			; save error flag
	CALLMAIN file::close

	plp			; restore error flag
	lda @err		; restore error code (if any)
@ret:	rts
.endproc

;*******************************************************************************
; INIT SEGMENTS
; Initializes segment addresses to 0
.proc init_segments
	ldx numsegments
	lda #$00
@l0:	sta segments_addrlo-1,x
	sta segments_addrhi-1,x
	sta segments_runaddrlo-1,x
	sta segments_runaddrhi-1,x
	dex
	bne @l0
	rts
.endproc

;*******************************************************************************
; UPDATE SEGMENTS
; Record absolute ranges. Relative usage is retained by link::fragment.
; OUT:
;   - .C: set if absolute SEGMENTs overlap or cannot be recorded
.proc update_segments
	ldx #$00
	cpx obj::numsegments
	beq @done

:	ldy obj::segment_ids,x		; get GLOBAL SEGMENT id from local one
	cpy #SEG_ABS			; ABS segments have no global SEGMENT
	bne @next

	; Preserve the local index while the absolute range is recorded.
	txa
	pha
	jsr add_absolute_segment
	sta objerr
	pla
	tax
	lda objerr
	bcs @ret

@next:	inx
	cpx obj::numsegments
	bne :-
@done:	RETURN_OK
@ret:	rts
.endproc

;*******************************************************************************
; ADD ABSOLUTE SEGMENT
; Adds a nonempty absolute SEGMENT range from the current object to the global
; absolute-range table. Errors on overlap with an earlier absolute SEGMENT.
; IN:
;   - .A: object-local SEGMENT index
; OUT:
;   - .C: set on overlap or if the range table is full
.proc add_absolute_segment
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
@ptr=ra
	tax
	lda obj::segments_sizelo,x
	ora obj::segments_sizehi,x
	jeq @ok				; empty SEGMENTs cannot overlap

	lda obj::segments_startlo,x
	sta @addr0_start
	ldy obj::segments_starthi,x
	sty @addr0_start+1
	clc
	adc obj::segments_sizelo,x
	sta @addr0_stop
	tya
	adc obj::segments_sizehi,x
	sta @addr0_stop+1
	bcs @outofrange			; SEGMENT end > $ffff

	ldxy #absolute_ranges
	stxy @ptr
@compare:
	ldxy @ptr
	cmpw absolute_end
	beq @store

	ldy #$00
	lda (@ptr),y
	sta @addr1_start
	iny
	lda (@ptr),y
	sta @addr1_start+1
	iny
	lda (@ptr),y
	sta @addr1_stop
	iny
	lda (@ptr),y
	sta @addr1_stop+1
	jsr ranges_overlap
	bcs @overlap

	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @compare
	inc @ptr+1
	jmp @compare

@store:
	ldxy absolute_end
	cmpw #absolute_ranges_end
	bcs @too_many

	ldy #$00
	lda @addr0_start
	sta (@ptr),y
	iny
	lda @addr0_start+1
	sta (@ptr),y
	iny
	lda @addr0_stop
	sta (@ptr),y
	iny
	lda @addr0_stop+1
	sta (@ptr),y

	lda absolute_end
	clc
	adc #$04
	sta absolute_end
	bcc @ok
	inc absolute_end+1

@ok:	RETURN_OK
@overlap:
	RETURN_ERR ERR_OVERLAPPING_SEGMENTS
@too_many:
	RETURN_ERR ERR_TOO_MANY_SEGMENTS
@outofrange:
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc

;*******************************************************************************
; SEGMIN
; Returns the minimum address found in the segments array, excluding SEGMENTs
; that are not part of the loadable image (see excluded_from_image)
.proc segmin
@min=r0
	ldx #$ff
	stx @min
	stx @min+1

	inx			; .X=0

@l0:	jsr excluded_from_image
	beq @next			; not in the image -> skip

	lda segments_addrhi,x
	cmp @min+1
	beq @chklo
	bcs @next

	sta @min+1
	lda segments_addrlo,x
	sta @min
	bcc @next

@chklo:	lda segments_addrlo,x
	cmp @min
	bcs @next
	sta @min
	lda segments_addrhi,x
	sta @min+1

@next:	inx
	cpx numsegments
	bne @l0

	ldxy @min
	rts
.endproc

;*******************************************************************************
; SEGMAX
; Returns the maximum address found in the segments array.  This is the base
; of the last SEGMENT + the size of it.  SEGMENTs that are not part of the
; loadable image are excluded (see excluded_from_image).
.proc segmax
@max=r0
@i=r2
	ldx #$00
	stx @i
	stx @max
	stx @max+1

@l0:	lda segments_addrhi,x
	cmp @max+1
	beq @chklo
	bcc @next

	jsr excluded_from_image
	beq @next			; not in the image -> skip

	sta @max+1
	lda segments_addrlo,x
	sta @max
	stx @i
	bcc @next

@chklo:	lda segments_addrlo,x
	cmp @max
	bcc @next

	jsr excluded_from_image
	beq @next			; not in the image -> skip
	sta @max
	lda segments_addrhi,x
	sta @max+1
	stx @i

@next:	inx
	cpx numsegments
	bne @l0

	lda @max
	clc
	ldy @i
	adc segments_sizelo,y
	tax
	lda @max+1
	adc segments_sizehi,y
	tay
	rts
.endproc

;*******************************************************************************
; EXCLUDED FROM IMAGE
; Returns .Z set if the given SEGMENT contributes nothing to the loadable image
; and must therefore not affect the program's ORIGIN or TOP (empty and zeropage
; SEGMENTs)
; IN:
;   - .X: the (0-based) index of the SEGMENT to test
; OUT:
;   - .Z: set if the SEGMENT must be excluded
; PRESERVES:
;   - .A
;   - .C (callers branch on the carry set before the call)
.proc excluded_from_image
@a=r3
	sta @a
	lda segments_type,x
	eor #TYPE_SEGZP		; EOR, unlike CMP, leaves .C alone
	beq @zp
	lda segments_type,x
	eor #TYPE_BSSZP
	beq @zp

	lda segments_sizelo,x
	ora segments_sizehi,x	; .Z set if the SEGMENT is empty
	jmp @done

@zp:	lda #$00		; .Z set -> exclude the SEGMENT

@done:	php			; save the result
	lda @a			; restore .A
	plp			; and the result
	rts
.endproc

;*******************************************************************************
; GET SECTION BY NAME
; Returns the ID of the section from its name
; IN:
;  - .XY: the name of the section
; OUT:
;  - .A: the ID of the section
;  - .C: set if no segment exists by the given name
.proc get_section_by_name
@name=zp::str0
@other=zp::str2
@cnt=r0
	stxy @name
	ldxy #section_names
	stxy @other

	lda #$00
	sta @cnt

@l0:	lda #$08
	jsr strcmp
	beq @found
	lda @other
	clc
	adc #$08
	sta @other
	bcc :+
	inc @other+1
:	ldx @cnt
	inx
	stx @cnt
	cpx numsections
	bcc @l0

@notfound:
	;sec
	rts

@found: lda @cnt
	RETURN_OK
.endproc



;*******************************************************************************
; SEGADDR BY ID
; Returns the (current) base address for the given SEGMENT id.
; IN:
;   - .A: global (linker) segment id to get the base address of
; OUT:
;   - .A:  the TYPE byte (BSS, RW, ZP, or ABS)
;   - .XY: the base address for the requested segment within objfile
.export __link_segaddr_by_id
.proc __link_segaddr_by_id
@tab=r2
	; get the segment-address table for the file
	tay
	lda segments_type-1,y		; get TYPE
	pha
	ldx segments_addrlo-1,y
	lda segments_addrhi-1,y
	tay
	pla				; restore TYPE byte
	RETURN_OK
.endproc



;*******************************************************************************
; SET SEGMENT TYPE
; Sets the type for the segment of the given ID.
; IN:
;   - .A: type to set
;   - .X: id of segment to set type for
; OUT:
;   - .C: set on error (segment is defined with conflicting type)
.export __link_set_segment_type
.proc __link_set_segment_type
	ldy segments_type-1,x
	cpy #SEG_UNDEF		; is segment still undefined?
	beq @set		; if so, continue

	; segment exists, validate that its TYPE matches
	cmp segments_type-1,x
	beq @done
	RETURN_ERR ERR_CONFLICTING_SEGMENTS

@set:	sta segments_type-1,x
@done:	RETURN_OK
.endproc

;*******************************************************************************
; GET SEGMENT BY NAME
; Returns the ID of the segment from its name
; IN:
;  - .XY: the name of the segment
; OUT:
;  - .A: the ID of the segment
;  - .C: set if no segment exists by the given name
.export __link_get_segment_by_name
__link_get_segment_by_name:
.proc get_segment_by_name
@name=zp::str0
@other=zp::str2
@cnt=r0
	stxy @name
	ldxy #segment_names
	stxy @other

	lda #$00
	sta @cnt
@l0:	lda #$08
	jsr strcmp
	beq @found
	lda @other
	clc
	adc #$08
	sta @other
	bcc :+
	inc @other+1
:	ldx @cnt
	inx
	stx @cnt
	cpx numsegments
	bcc @l0

@notfound:
	;sec
	lda #ERR_UNKNOWN_SEGMENT
	rts

@found: lda @cnt
	clc
	adc #$01		; get 1-based id
	;clc
	rts
.endproc

;*******************************************************************************
; READ KEY
; Read the key in a key/value pair into the given buffer
; A key/value pair is a string and value separated by an '=' sign
; IN:
;   - zp::line: the buffer to read the key from
;   - .XY:      the address to read the key into
; OUT:
;   - zp::line: updated to point after the '=' in the key/value pair
;   - .C:       set if the input buffer is not a valid key/value pair
.proc readkey
@buff=r0
	stxy @buff

	ldy #$00
@l0:	lda (zp::line),y
	jsr is_newl
	beq @err	; unexpected newline
	cmp #'='
	beq @done	; found end of key definition
	sta (@buff),y
	iny
	cpy #8
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG

@done:	lda #$00
	sta (@buff),y	; terminate bufffer
	tya
	sec		; +1
	adc zp::line
	sta zp::line
	bcc :+
	inc zp::line+1
:	RETURN_OK

@err:	RETURN_ERR ERR_UNEXPECTED_CHAR
.endproc

;*******************************************************************************
; PARSE VAL
; Parses the value from the key/value pair
; e.g. A=120
; IN:
;   - zp::line: points to the value of a key/value pair
; OUT:
;   - zp::line: points after the value in the buffer
;   - .XY:      the value of the key/value pair
;   - .C:       set if the key/value pair was not parsed successfully
.proc parse_val
@val=r0
@buff=$100
	jsr process_ws

	; read the value into a temporary buffer
@l0:	lda (zp::line),y
	beq :+
	jsr is_newl
	beq :+
	cmp #';'	; SEGMENT/SECTION terminator
	beq :+
	sta @buff,y
	iny
	bne @l0

:	lda #$00
	sta @buff,y
	tay

	; check if the value is hex or decimal
	lda (zp::line),y
	cmp #'$'
	beq @hex

@dec:	ldxy #@buff
	CALLMAIN atoi
	bcc @cont
	rts			; error

@hex:	; get the value of the value string
	ldxy #@buff+1		; +1 to get after the '$'
	CALLMAIN util::parsehex
	bcs @ret

@cont:	stxy @val
	; move beyond the value string (to start of next word or ';')
	ldy #$00
:	lda (zp::line),y
	jsr is_newl
	beq @done
	cmp #';'
	beq @done
	iny
	jsr is_ws
	bne :-

@done:	tya
	clc
	adc zp::line
	sta zp::line
	bcc :+
	inc zp::line+1
:	ldxy @val
	clc		; ok
@ret:	rts
.endproc

;*******************************************************************************
; PARSE NUM
; Parses the number in the given 0-terminated buffer.  The number may be given
; in decimal or, with a '$' prefix, in hexadecimal.
; Unlike parse_val, this reads a value that has already been copied out of the
; LINK file (see the SEGMENT key handlers, which are given their value in a
; buffer) and so leaves zp::line alone.
; IN:
;   - .XY: the buffer holding the number to parse
; OUT:
;   - .XY: the value that was parsed
;   - .C:  set if the buffer does not hold a valid number
.proc parse_num
@buff=r0
	stxy @buff
	ldy #$00
	lda (@buff),y
	cmp #'$'
	beq @hex

@dec:	ldxy @buff
	JUMPMAIN atoi

@hex:	incw @buff		; move over the '$'
	ldxy @buff
	JUMPMAIN util::parsehex
.endproc

;*******************************************************************************
; COMPARE LINE
; Compares the strings in (zp::line) and (.XY) up to a length of .A
.proc cmpline
	stxy zp::str2
	ldxy zp::line
	stxy zp::str0

	; fall through to strcmp
.endproc

;*******************************************************************************
; COMPARE
; Compares the strings in (zp::str0) and (zp::str2) up to a length of .A
; IN:
;  zp::str0: one of the strings to compare
;  zp::str2: the other string to compare
; OUT:
;  .Z: set if the strings are equal
.proc strcmp
	ldy #$00
@l0:	lda (zp::str0),y
	beq :+
	jsr is_ws
	beq :+
	cmp (zp::str2),y
	bne @ret
	iny
	bne @l0

:	lda (zp::str2),y	; make sure strings terminate at same index
@ret:	rts
.endproc

;*******************************************************************************
; PROCESS WS
; Reads (line) and updates it to point past ' ' chars and non-printing chars
; out:
;  .Z: set if we're at the end of the line
;  .A: the last character processed
;  .Y: 0
;  zp::line: updated to first non ' ' character
.proc process_ws
	ldy #$00
@l0:	lda (zp::line),y
	beq @done		; if end of line, we're done
	bmi @skip		; skip non-printing chars
	jsr is_ws
	bne @done		; if not space, we're done
@skip:	incw zp::line
	bne @l0
@done:	rts
.endproc

;*******************************************************************************
; IS NEWL
; Checks if the given character is a newline ($0d or $0a)
; IN:
;  - .A: the character to test
; OUT:
;  - .Z: set if if the character in .A is whitespace
.proc is_newl
	cmp #$0d	; newline
	beq :+
	cmp #$0a	; UNIX newline
:	rts
.endproc

;*******************************************************************************
; IS WS
; Checks if the given character is a whitespace character
; IN:
;  - .A: the character to test
; OUT:
;  - .Z: set if if the character in .A is whitespace
.proc is_ws
	cmp #$0d	; newline
	beq :+
	cmp #$09	; TAB
	beq :+
	cmp #$0a	; UNIX newline
	beq :+
	cmp #' '
:	rts
.endproc

;*******************************************************************************
; GENERATE MAP
; Write a "MAP" file containing all the SEGMENTS and SYMBOLS that were
; used in the creation of the linked program
.proc generate_map
@i=r2
@tmp=r4
@name=r6
@symbuff=$100
	; check if there is already a MAP file
	ldxy #@filename
	CALLMAIN file::exists
	cmp #$00
	bne @new

	; scratch the existing MAP file if it exists
	ldxy #@filename
	CALLMAIN file::scratch
	bcs @err

@new:	ldxy #@filename
	CALLMAIN file::open_w
	bcc :+
@err:	rts

:	pha				; save file handle
	tax
	jsr krn::chkout			; CHKOUT

	lda #$00
	sta @i
	cmp numsegments
	jeq @symbols

@segments:
	ldxy #@seglist_title
	jsr puts		; write the "segments" title
	jsr write_h_line
	ldxy #@seglist_header
	jsr puts		; write the "segments" header

	; write the name, address, and size of each segment
	ldxy #segment_names
	stxy @name
	lda #$00
	sta @i

@segloop:
	ldy #$00
:	lda (@name),y
	beq :+
	jsr krn::chrout
	iny
	cpy #MAX_SEGMENT_NAME_LEN
	bne :-

:	; write 8-len(name)+1 spaces of padding
	sty @tmp
	lda #8
	sec
	sbc @tmp
	tay
	lda #' '
:	jsr krn::chrout
	dey
	bpl :-

@segstart:
	ldx @i
	ldy segments_addrhi,x	; LOAD address (MSB)
	lda segments_addrlo,x	; LOAD address (LSB)
	tax
	jsr putword

	; padding between LOAD and RUN
	lda #' '
	jsr krn::chrout
	jsr krn::chrout

@segrun:
	ldx @i
	ldy segments_runaddrhi,x	; RUN address (MSB)
	lda segments_runaddrlo,x	; RUN address (LSB)
	tax
	jsr putword

	; padding between RUN and size
	lda #' '
	jsr krn::chrout
	jsr krn::chrout

@segsize:
	ldx @i
	ldy segments_sizehi,x	; get the size (MSB)
	lda segments_sizelo,x	; get the size (LSB)
	tax
	jsr putword

@nextseg:
	lda #$0d
	jsr krn::chrout

	lda @name
	clc
	adc #MAX_SEGMENT_NAME_LEN
	sta @name
	bcc :+
	inc @name+1

:	inc @i
	lda @i
	cmp numsegments
	bne @segloop

@symbols:
	lda #$0d
	jsr krn::chrout

	ldxy #@symbols_title
	jsr puts		; write the "symbols" title
	jsr write_h_line
	ldxy #@symbols_header
	jsr puts		; write the "symbols" header

	; write the name, address, and address mode of each symbol
	ldxy #$00
	stxy @i
	cmpw lbl::num
	beq @done

@symloop:
	ldxy #@symbuff
	stxy r0
	ldxy @i
	CALLMAIN lbl::getname
	ldxy #@symbuff
	jsr puts

	; write 32-len(labelname)+1 spaces
	sty @tmp
	lda #32
	sec
	sbc @tmp
	tay
	lda #' '
:	jsr krn::chrout
	dey
	bpl :-

	; write the label's address
	ldxy @i
	CALLMAIN lbl::addr_and_mode
	cmp #$00					; zeropage?
	beq @zp
@abs:	jsr putword
	jmp @nextsym
@zp:	jsr putbyte
@nextsym:
	lda #$0d
	jsr krn::chrout
	incw @i
	ldxy @i
	cmpw lbl::num
	bne @symloop

@done:	pla					; restore file handle
	CALLMAIN file::close
	JUMPMAIN file::geterr			; report write errors
						; (e.g. disk full)

;-------------------------------------------------------------------------------
@seglist_title:  .byte "segments",$0d,0
@seglist_header: .byte "name     load   run    size",$0d,0
@symbols_title:  .byte "symbols",$0d,0
@symbols_header: .byte "name                             addr",$0d,0

.PUSHSEG
.RODATA
@filename:       .byte "map",0
.POPSEG
.endproc

;*******************************************************************************
; VALIDATE SEGMENTS
; Checks if any named or absolute segments generated during linking overlap
; OUT:
;   - .A: error code (if validation failed)
;   - .C: set if any two segments overlap
.proc validate_segments
@i=r0
@j=r1
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
@ptr=ra
	lda numsegments
	jeq @ok

	lda #$00
	sta @i

@l0:	ldx @i
	; skip empty segments (they can't overlap anything)
	lda segments_sizelo,x
	ora segments_sizehi,x
	beq @nexti

	lda segments_addrlo,x
	sta @addr0_start
	ldy segments_addrhi,x
	sty @addr0_start+1
	clc
	adc segments_sizelo,x
	sta @addr0_stop
	tya
	adc segments_sizehi,x
	sta @addr0_stop+1

	ldx @i
	stx @j

@l1:	inc @j
	ldx @j
	cpx numsegments
	bcs @nexti

	; skip empty segments
	lda segments_sizelo,x
	ora segments_sizehi,x
	beq @l1

	lda segments_addrlo,x
	sta @addr1_start
	ldy segments_addrhi,x
	sty @addr1_start+1
	clc
	adc segments_sizelo,x
	sta @addr1_stop
	tya
	adc segments_sizehi,x
	sta @addr1_stop+1

	jsr ranges_overlap
	bcs @overlap
	bcc @l1			; branch always

@nexti:	inc @i
	lda @i
	cmp numsegments
	bcc @l0

	; compare all absolute ranges with every named global SEGMENT now that
	; their origins are known
	ldxy #absolute_ranges
	stxy @ptr
@absolute_loop:
	ldxy @ptr
	cmpw absolute_end
	beq @ok

	ldy #$00
	lda (@ptr),y
	sta @addr0_start
	iny
	lda (@ptr),y
	sta @addr0_start+1
	iny
	lda (@ptr),y
	sta @addr0_stop
	iny
	lda (@ptr),y
	sta @addr0_stop+1

	lda #$00
	sta @j
@absolute_global_loop:
	ldx @j
	lda segments_sizelo,x
	ora segments_sizehi,x
	beq @next_absolute_global

	lda segments_addrlo,x
	sta @addr1_start
	ldy segments_addrhi,x
	sty @addr1_start+1
	clc
	adc segments_sizelo,x
	sta @addr1_stop
	tya
	adc segments_sizehi,x
	sta @addr1_stop+1

	jsr ranges_overlap
	bcs @overlap

@next_absolute_global:
	inc @j
	lda @j
	cmp numsegments
	bcc @absolute_global_loop

	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @absolute_loop
	inc @ptr+1
	jmp @absolute_loop

@ok:
	RETURN_OK

@overlap:
	RETURN_ERR ERR_OVERLAPPING_SEGMENTS
.endproc

;-------------------------------------------------------------------------------
; checks if [addr0_start, addr0_stop) overlaps [addr1_start, addr1_stop)
; overlap iff addr0.start < addr1.stop AND addr1.start < addr0.stop
; OUT:
;   - .C: set if the ranges overlap
.proc ranges_overlap
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
	; if addr0.start >= addr1.stop, no overlap
	lda @addr0_start
	cmp @addr1_stop
	lda @addr0_start+1
	sbc @addr1_stop+1
	bcs @no_overlap

	; if addr1.start >= addr0.stop, no overlap
	lda @addr1_start
	cmp @addr0_stop
	lda @addr1_start+1
	sbc @addr0_stop+1
	bcs @no_overlap

	sec			; overlap
	rts

@no_overlap:
	clc
	rts
.endproc

;*******************************************************************************
; WRITE H LINE
; Writes a line of '-'s
.proc write_h_line
	lda #'-'
	ldy #LINESIZE
:	jsr krn::chrout
	dey
	bne :-
	lda #$0d
	jsr krn::chrout
	rts
.endproc

;*******************************************************************************
; PUTBYTE
; Outputs the given byte as a hex value
; IN:
;   - .X: the value to output
.proc putbyte
	lda #'$'
	jsr krn::chrout

	txa
	CALLMAIN util::hextostr
	tya
	jsr krn::chrout
	txa
	jmp krn::chrout
.endproc

;*******************************************************************************
; PUTWORD
; Outputs the given word as a hex value
; IN:
;   - .XY: the value to output
.proc putword
	lda #'$'
	jsr krn::chrout

	txa
	pha
	tya
	CALLMAIN util::hextostr
	tya
	jsr krn::chrout
	txa
	jsr krn::chrout
	pla
	CALLMAIN util::hextostr
	tya
	jsr krn::chrout
	txa
	jmp krn::chrout
.endproc

;*******************************************************************************
; PUTS
; Writes a 0-terminated string to the open file
; IN:
;   - .XY: the address of the string to output
; OUT:
;   - .Y: the length of the string written
.proc puts
@str=zp::str0
	stxy @str

	ldy #$00
:	lda (@str),y
	beq @done
	jsr krn::chrout
	iny
	bne :-

@done:	rts
.endproc

;*******************************************************************************
; LOG NEWL
; Logs a newline
.proc log_newl
	ldxy #strings::null
	JUMPMAIN log::out
.endproc

;*******************************************************************************
; LOG MSG
; Copies the provided string to shared RAM and logs it
; IN:
;   - .XY: address of string to log
.proc log_msg
@ret=r4
@str=r4
@buff=$100
	stxy @str

	; copy the string to RAM
	ldy #$ff
:	iny
	lda (@str),y
	sta @buff,y
	cmp #$00
	bne :-

	pla
	sta @ret
	pla
	sta @ret+1

	ldxy #@buff
	RENDER_STR			; render the string
	CALLMAIN log::out		; and log it

	lda @ret+1
	pha
	lda @ret
	pha
	rts
.endproc

;*******************************************************************************
; LOG BANNER
; Logs a '*' banner
.proc log_banner
	JUMPMAIN log::banner
.endproc

;*******************************************************************************
; CAPITALIZE
; Capitalizes the input character
; IN:
;   - .A: character to capitalize
; OUT:
;   - .A: capitalized version of input character
.proc capitalize
	cmp #$61
	bcc @done
	cmp #$7a+1
	bcs @done
	eor #$20	; to upper
@done:	rts
.endproc
