;*******************************************************************************
; LINKER.ASM
; The linker links the object code generated by the assembler into a binary
; (.prg or plain) or debug (.d) file.
;
; See the OBJECT CODE overview below for details on the object format.
;*******************************************************************************

.include "asm.inc"
.include "config.inc"
.include "debuginfo.inc"
.include "edit.inc"
.include "errors.inc"
.include "file.inc"
.include "kernal.inc"
.include "key.inc"
.include "keycodes.inc"
.include "labels.inc"
.include "limits.inc"
.include "linkfragments.inc"
.include "line.inc"
.include "log.inc"
.include "macros.inc"
.include "math.inc"
.include "memory.inc"
.include "object.inc"
.include "screen.inc"
.include "string.inc"
.include "strings.inc"
.include "symbolpages.inc"
.include "util.inc"
.include "target.inc"
.include "text.inc"
.include "zeropage.inc"

.include "ram.inc"
.include "image.inc"

.macpack longbranch

.import __LINKER_BSS_LOAD__
.import __LINKER_BSS_SIZE__

;*******************************************************************************
; CONSTANTS
MAX_SECTIONS         = MAX_LINK_SECTIONS	; max number of memory sections
MAX_SECTION_NAME_LEN = 8	; section name storage, including terminator
MAX_SEGMENT_NAME_LEN = 8	; segment name storage, including terminator

MAX_SYMBOLS         = 128	; max # of symbols per object file

SYM_IMPORT_BYTE     = 1
SYM_IMPORT_WORD     = 2
SYM_REL_EXPORT_BYTE = 3
SYM_REL_EXPORT_WORD = 4
SYM_ABS_EXPORT_BYTE = 5
SYM_ABS_EXPORT_WORD = 6

;*******************************************************************************
; SECTION flags
SECTION_OFFSET = $02
SECTION_FILL = $01	; flag to pad section's unused bytes with 0
SECTION_NOEMIT = $04	; address-only region, excluded from output
SEGMENT_DEFINE = $01	; publish layout constants after placement

; LINK definition properties seen while parsing
SECTION_PROP_START     = $01
SECTION_PROP_END       = $02
SECTION_PROPS_REQUIRED = SECTION_PROP_START | SECTION_PROP_END

SEGMENT_PROP_LOAD      = $01
SEGMENT_PROP_RUN       = $02
SEGMENT_PROPS_REQUIRED = SEGMENT_PROP_LOAD

;*******************************************************************************
; ZEROPAGE variables
; OBJPTR is the cursor in the object code (where we are reading in the current
; object file)
; SEGPTR is the cursor to the .PRG or .D file (where we are WRITIING)
objptr=zp::link
segptr=zp::link+2
link_filename=mem::spare+$180 ; shared across calls, below symbol scratch

;*******************************************************************************
; OBJFILES
; The list of object files to link
; Represented as a 0-terminated list of 0-terminated filename
; e.g.
;   "FILE1.O",0,"FILE2.O",0,0

.export __link_objfiles
.ifdef vic20
.segment "LINKER_BSS"
__link_objfiles: .res MAX_OBJS*17+1
.else
__link_objfiles=mem::spare
.endif
.export __link_objfiles_end
__link_objfiles_end = __link_objfiles + MAX_OBJS*17+1
.ifndef vic20
.assert MAX_OBJS*17+1 <= $180, error, "object list overlaps shared filename"
.endif
.assert $180+17 <= $200, error, "shared filename overlaps symbol scratch"

;*******************************************************************************
.segment "LINKER_VARS"

numsegments: .byte 0
numsections: .byte 0

activeobj:         .byte 0	; the current OBJECT (id) being linked
objerr:            .byte 0	; error code from linking an object
parsed_properties: .byte 0	; properties seen in the current LINK definition
absolute_end:      .word 0	; next free entry in absolute_ranges
layout_loadbank:   .byte 0
layout_runbank:    .byte 0
layout_sizebank:   .byte $00
linkpass:          .byte 0	; 1 while pass 1 is running, 2 during pass 2

;*******************************************************************************
; OBJECT STATE
; These variables are used in the context of a single object file
numsymbols:  .byte 0

.segment "LINKER_BSS"

; Stores fragment records in object/header order. Each object's base pointer
; locates its first record; symbol owners select the corresponding object.
fragments_top: .word 0		; first unused record throughout both link passes
object_fragbase_lo: .res MAX_OBJS
object_fragbase_hi: .res MAX_OBJS
fragments: .res MAX_LINK_FRAGMENTS*FR_BYTES
fragments_end = *

;*******************************************************************************
; SECTIONS
; The memory section contains up to MAX_SECTIONS of memory blocks.  Each
; defines the start and end addresses of the section plus a byte of flag
; data, which is used to, for example, flag that the section should be padded
; if the SEGMENTs that map to this section do not span the entire
; [start, stop) address space.
; The format of a SECTION is:
;  .word start addr
;  .word stop addr
;  .byte flags
sections_startlo:    .res MAX_SECTIONS
sections_starthi:    .res MAX_SECTIONS
sections_stoplo:     .res MAX_SECTIONS
sections_stophi:     .res MAX_SECTIONS
sections_stopbank:   .res MAX_SECTIONS	; must be $00 or $01 (END=$10000)
sections_flags:      .res MAX_SECTIONS
section_names:       .res MAX_SECTIONS*MAX_SECTION_NAME_LEN
sections_offsetlo:   .res MAX_SECTIONS
sections_offsethi:   .res MAX_SECTIONS
sections_offsetbank: .res MAX_SECTIONS
sections_banklo:     .res MAX_SECTIONS	; physical bank, independent of OFFSET
sections_bankhi:     .res MAX_SECTIONS
section_cursorlo:    .res MAX_SECTIONS
section_cursorhi:    .res MAX_SECTIONS
section_cursorbank:  .res MAX_SECTIONS

.export sections_startlo
.export sections_starthi
.export sections_stoplo
.export sections_stophi
.export sections_flags
.export section_names

;*******************************************************************************
; SEGMENTS
; Segments define where the code or data that occupies them will be mapped to
; the memory defined in the SECTIONS blocks
; SEGMENTs may LOAD to one address but RUN in another. Note the corresponding
; bytes in the SEGMENT structure that select this.
;
; SEGMENTs have the format:
;  .byte[8] name
;  .byte    LOAD SEGMENT id
;  .byte    RUN SEGMENT id
;  .byte    flags
segments_load:     .res MAX_SEGMENTS	; id of SECTION to load to
segments_run:      .res MAX_SEGMENTS	; id of SECTION to run at
segments_flags:    .res MAX_SEGMENTS
segments_sizelo:   .res MAX_SEGMENTS
segments_sizehi:   .res MAX_SEGMENTS
segments_sizebank: .res MAX_SEGMENTS	; must be $00 or $01 (full bank)
segments_type:     .res MAX_SEGMENTS

; The alignment required of each SEGMENT: the LINK file's ALIGN property
; combined (see lcm16) with the alignment every object file asks of the SEGMENT
; through its .ALIGN directives.  0 or 1 means the SEGMENT is unaligned.
; Alignments need not be powers of 2, so rounding goes through align_up.
segments_alignlo: .res MAX_SEGMENTS
segments_alignhi: .res MAX_SEGMENTS

; pointers for the current LOAD address of each SEGMENT during linking.
; This is where the SEGMENT's bytes are placed in the output image.
segments_addrlo: .res MAX_SEGMENTS
segments_addrhi: .res MAX_SEGMENTS
segments_addrbank: .res MAX_SEGMENTS	; upper address byte (exclusive $10000 endpoint)

; pointers for the current RUN address of each SEGMENT during linking.
; This is the address the SEGMENT's code is relocated for; it differs from the
; LOAD address when the SEGMENT declares a RUN SECTION of its own (the program
; is expected to copy the SEGMENT from LOAD to RUN before executing it).
segments_runaddrlo: .res MAX_SEGMENTS
segments_runaddrhi: .res MAX_SEGMENTS
segments_runaddrbank: .res MAX_SEGMENTS	; upper address byte, not physical bank

segment_names: .res MAX_SEGMENT_NAME_LEN*MAX_SEGMENTS

; Stores absolute SEGMENT ranges as start/stop word pairs, one per fragment.
.if .defined(c64) .and .defined(CART)
.pushseg
; Stores absolute ranges in always-visible high RAM.
.segment "LINKER_RANGES"
.endif
absolute_ranges: .res MAX_LINK_FRAGMENTS*4
absolute_ranges_end = *
.if .defined(c64) .and .defined(CART)
.popseg
.endif

.export segments_load
.export segments_run
.export segments_flags
.export segments_sizelo
.export segments_sizehi
.export segments_alignlo
.export segments_alignhi
.export segment_names

;*******************************************************************************
; OBJECT CODE overview
; See object.asm for the byte-level format. Headers describe ordered
; object-local fragments of named SEGMENTs, followed by symbols, code,
; relocation tables and debugger line programs.
;
; Pass 1 collects fragment sizes and alignment constraints. Layout assigns
; each fragment fixed LOAD/RUN bases, including padding, then resolves symbols
; as fragment RUN base + offset. Pass 2 emits padding/code and relocates each
; operand at its containing fragment's fixed address. Neither symbols nor
; branches assume that offsets in different fragments share a displacement.
;*******************************************************************************

;*******************************************************************************
; DEBUG FILE overview
; Debug (.d) files are binary files that contain the linked object code.
; They are similar to the object files that they are built from.
;
; Debug files cannot be run outside the Monster environment. To produce a
; standalone .PRG use dbg::linkprg
;
; EXAMPLE:
;  FILE NAMES:
;   hello.s
;   main.s
;
;  NUM_SYMBOLS: 4
;
;  SYMBOLS:
;   LAB1     CODE+$1600  hello.s L:120
;   LAB2     CODE+$1402  hello.s L:40
;   my_proc  CODE+$1000  main.s  L:200
;   my_proc2 SETUP+$20   main.s  L:10
;
;  SEGMENTS:
;   CODE $1032
;   DATA $062
;*******************************************************************************

;*******************************************************************************
; OBJ Code Opcodes
; These represent the "instruction" opcodes of the object code
OBJ_SETSEG  = $01       ; switches to the given segment e.g. "SEG DATA"
OBJ_BYTES   = $02 	; RLE encoded byte values e.g. "B 4 0 1 2 3"
OBJ_RELBYTE = $03	; byte value + word offset "RB LAB+3"
OBJ_RELWORD = $04	; word value + word offset "RW LAB+10"
OBJ_RELZP   = $05	; byte value followed by relative byte "RZ $20 LAB+10"
OBJ_RELABS  = $06	; byte value followed by relative word "RA $20 LAB+5"

BANKED_SEG "LINKER", FINAL_BANK_LINKER

;*******************************************************************************
; INIT
; Initializes the linker state
; IN:
;   - None
; OUT:
;   - None
.export __link_init
.proc __link_init
@bss=r0
	; clear the LINKER_BSS segment
	ldxy #__LINKER_BSS_LOAD__
	stxy @bss

	lda #$00
@l0:	ldy #$00
	tya
	sta (@bss),y
	incw @bss
	ldxy @bss
	cmpw #__LINKER_BSS_LOAD__+__LINKER_BSS_SIZE__
	bne @l0

	lda #$00
	sta numsegments
	sta numsections
	sta image::mapped
	lda #$01
	sta image::mode
	sta activeobj
	sta linkpass
	ldxy #absolute_ranges
	stxy absolute_end

	rts
.endproc

;*******************************************************************************
; PARSE LINK FILE
; Parses the given linker config file into sections and segments, loading
; those into the linker's own section and segment state.
; The file must follow the format:
;
; ```
; MEMORY [
; SECTIONA:
;  start=$0000
;  end=$1000
; SECTIONB:
;  ...
; ]
; SEGMENTS [
;  SEGA: load = SECTIONA
;  run = SECTIONB
; ]
; ```
;
; IN:
;  - .XY: pointer to the link filename
;  - .A:  length of the filename
; OUT:
;  - .C: set if the file could not be successfully opened or parsed
.export __link_parse
.proc __link_parse
; Stores LINK text in the fragment buffer while parsing the configuration.
@filebuff=fragments
@filebuff_end=fragments_end
@segments_declared=r8
@sections_declared=r9
@buff=ra
@errcode=r0
	; set default TYPE attribute (all segments as UNDEF)
	ldy #MAX_SEGMENTS
	lda #TYPE_UNDEF
:	sta segments_type-1,y
	dey
	bne :-

	; load link file into filebuff
	ldxy #strings::link
	CALLMAIN file::open_r
	bcc :+
	rts					; failed to open the link file
:	pha					; save file ID
	tax
	jsr krn::chkin

	; read the file into the buffer (until EOF)
	ldxy #@filebuff
	stxy @buff
@readfile:
	jsr update_progress
	ldxy @buff
	cmpw #@filebuff_end		; is the buffer full?
	bcs @toobig
	jsr krn::chrin
	ldy #$00
	jsr capitalize			; uppercase the input
	sta (@buff),y
	incw @buff
	jsr krn::readst
	cmp #$00
	beq @readfile

	; read done; map KERNAL status to an internal error code
	cmp #$40			; EOF is the only clean way to finish
	beq @readok
	lda #ERR_IO_ERROR		; any other status is a read failure
	bne @closefile			; branch always

@toobig:
	lda #ERR_FILE_TOO_BIG
	skw
@readok:
	lda #$00
;-------------------------------------------------------------------------------
@closefile:
	sta @errcode
	pla				; restore file ID
	CALLMAIN file::close		; CLOSE the LINK file

	lda @errcode
	beq @parse			; no read error -> parse the buffer
	sec
	rts				; return read error

@parse:
	ldxy #@filebuff
	stxy zp::line

	lda #$00
	sta @sections_declared
	sta @segments_declared

@getblock:
	; have all required blocks been declared?
	lda @sections_declared
	and @segments_declared
	beq @read_block

	; done, make sure rest of file is whitespace
:	ldy #$00
	lda (zp::line),y
	jsr is_ws
	bne @unexpected_char
	incw zp::line
	ldxy zp::line
	cmpw @buff
	bne :-
@done:	RETURN_OK

;-------------------------------------------------------------------------------
@read_block:
	; look for MEMORY or SEGMENTS definition
	jsr process_ws
	ldy #$00

	; is line "MEMORY"?
	ldxy #@memory
	jsr cmpline
	beq @parse_sections

	; else is line "SEGMENTS"?
	ldxy #@segments
	jsr cmpline
	beq @parse_segments

	; else invalid string
	RETURN_ERR ERR_SYNTAX_ERROR	; not a MEMORY or SEGMENTS block

@err:	rts			; propagate the error code already in .A

@too_many:
	RETURN_ERR ERR_TOO_MANY_SEGMENTS

;-------------------------------------------------------------------------------
@parse_sections:
	; make sure we haven't already declared sections
	lda @sections_declared
	beq :+
	RETURN_ERR ERR_DUPLICATE_BLOCK	; MEMORY block already declared

:	; read past "MEMORY" declaration
	jsr process_word
	inc @sections_declared

	; look for the '['
	jsr @get_open_brace
	beq :+
@unexpected_char:
	RETURN_ERR ERR_UNEXPECTED_CHAR

	; read the section into the section definitions table
:	incw zp::line		; move beyond the '['
	jsr process_ws
@l0:	lda numsections
	cmp #MAX_SECTIONS	; is there room for another SECTION?
	bcs @too_many
	jsr parse_section
	bcs @err		; -> rts
	inc numsections		; SECTION was successfully parsed

	jsr @get_closing_brace
	bne @l0			; if not ']', read next section
	incw zp::line		; else, move over the ']'
	jmp @getblock		; and get the next block (SEGMENTS)

;-------------------------------------------------------------------------------
@parse_segments:
	; make sure SEGMENTS weren't already declared
	lda @segments_declared
	beq :+
	RETURN_ERR ERR_DUPLICATE_BLOCK	; SEGMENTS block already declared

:	; read past "SEGMENTS"
	jsr process_word
	inc @segments_declared

	; look for the '['
	jsr @get_open_brace
	beq :+
	RETURN_ERR ERR_UNEXPECTED_CHAR

	; read the section into the section definitions table
:	incw zp::line		; move beyond the '['
	jsr process_ws
@l1:	lda numsegments
	cmp #MAX_SEGMENTS	; is there room for another SEGMENT?
	bcs @too_many
	jsr parse_segment
	bcs @err		; -> rts
	inc numsegments		; SEGMENT was successfully parsed
	jsr @get_closing_brace
	bne @l1			; if not ']', read next segment
	incw zp::line		; else, move over the ']'
	jmp @getblock		; and get next block (SECTIONS)

;-------------------------------------------------------------------------------
; return .Z set if first non-whitespace char is a '['
@get_open_brace:
	jsr process_ws
	ldy #$00
	lda (zp::line),y
	cmp #'['
	rts

;-------------------------------------------------------------------------------
; return .Z set if first non-whitespace char is a ']'
@get_closing_brace:
	jsr process_ws
	ldy #$00
	lda (zp::line),y
	cmp #']'
	rts

;-------------------------------------------------------------------------------
@memory:   .byte "memory",0
@segments: .byte "segments",0
.endproc

;*******************************************************************************
; PARSE SECTION
; Parses the definition for one SECTION in the MEMORY block of the linker file
; A section is defined by the section name followed by a ':'
; Followed by lines defining its start and end address
;
; SECTIONA:
;  start=$0000
;  end=$1000
;  fill=1
;
; IN:
;  - zp::line: points to the buffer to parse the SECTION from
; OUT:
;  - .C: set if section could not be parsed
.proc parse_section
@name=r0
@val=r2
@cnt=r4
@keybuff=$100
	lda #$00
	sta parsed_properties

	; get address to store new section name to
	lda #$00
	sta @name+1
	lda numsections
	asl			; *2
	rol @name+1
	asl			; *4
	rol @name+1
	asl			; *8
	rol @name+1
	clc
	adc #<section_names
	sta @name
	lda @name+1
	adc #>section_names
	sta @name+1

	; read the section name (string terminated by ':')
	jsr process_ws
	ldy #$00
@l0:	lda (zp::line),y
	bne :+
@err:	RETURN_ERR ERR_UNEXPECTED_CHAR	; line ended without ':'
:	jsr is_newl
	beq @err
	cmp #':'
	beq @cont			; found end of section name
	sta (@name),y
	iny
	cpy #$08
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG	; section name > 8 chars

@cont:	tya
	;sec			; +1 (move pointer after the ':')
	adc zp::line
	sta zp::line
	bcc @check_duplicate
	inc zp::line+1

@check_duplicate:
	; numsections does not include the section currently being parsed
	lda numsections
	beq @getprops
	ldxy @name
	jsr get_section_by_name
	bcs @getprops
	RETURN_ERR ERR_DUPLICATE_NAME

; read all properties defined for the SECTION
@getprops:
	jsr process_ws		; move the key name in section

	ldy #$00
	lda (zp::line),y
	cmp #';'		; are we at the end of the section?
	bne @read_property

	; make sure section declared all required properties
	lda parsed_properties
	and #SECTION_PROPS_REQUIRED
	cmp #SECTION_PROPS_REQUIRED
	beq @properties_ok
	RETURN_ERR ERR_MISSING_REQUIRED_KEY

@properties_ok:
	ldx numsections
	lda sections_flags,x
	and #SECTION_NOEMIT
	beq :+
	lda sections_flags,x
	and #(SECTION_OFFSET | SECTION_FILL)
	beq :+
	RETURN_ERR ERR_CONFLICTING_SEGMENTS
:
	lda sections_stoplo,x
	cmp sections_startlo,x
	lda sections_stophi,x
	sbc sections_starthi,x
	lda sections_stopbank,x
	sbc #$00
	bcs :+
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
:	incw zp::line		; move beyond the semicolon
	RETURN_OK		; we're at the end, return

@read_property:
	; read the key of the k/v pair into keybuffer
	ldxy #@keybuff
	jsr readkey
	jcs @err

@keyfound:
	ldxy #@keybuff
	stxy zp::str0

	; find the key that corresponds to the one in the config file
	ldxy #@keys
	stxy zp::str2

	lda #$00
	sta @cnt
@findkey:
	jsr strcmp
	bne @next

	; Evaluate offsets and CPU bounds with checked endpoint arithmetic.
@found:	ldx @cnt
	CALL FINAL_BANK_LINKER_AUX, parse_section_property
	jcc @getprops	; repeat (get next key if there is one)
	jcs log_error	; handler failed -> return its error

@next:	; move zp::str2 to the next key to check
	ldy #$00
:	lda (zp::str2),y
	incw zp::str2
	cmp #$00
	bne :-

	; are we out of keys?
	inc @cnt
	lda @cnt
	cmp #@numkeys
	bne @findkey
	RETURN_ERR ERR_UNKNOWN_KEY	; no key matched the one in the file

@ret:	rts

;-------------------------------------------------------------------------------
; keys table
@keys:
@numkeys=$06
@start:	.byte "start",0
@end:	.byte "end",0
@fill:	.byte "fill",0
	.byte "offset",$00
	.byte "emit",$00
	.byte "bank",$00

.endproc

;*******************************************************************************
; PARSE SEGMENT
; Parses the definition for one SEGMENT in the SEGMENTS block of the linker file
; A segment is defined by the section name followed by a ':'
; Followed by lines defining its load and run addresses
; SEGA:
;  load=$0000
;  run=$1000
; IN:
;  - zp::line: points to the buffer to parse the SEGMENT from
; OUT:
;  - .C: set if the segment could not be parsed
.proc parse_segment
@name=r0
@val=r2
@cnt=r4
@alignval=r6
@keybuff=$100
@valbuff=$100
	lda #$00
	sta parsed_properties

	; get address to store new segment name to
	lda #$00
	sta @name+1
	lda numsegments
	asl			; *2
	rol @name+1
	asl			; *4
	rol @name+1
	asl			; *8
	rol @name+1
	adc #<segment_names
	sta @name
	lda @name+1
	adc #>segment_names
	sta @name+1

	; read the segment name (string terminated by ':')
	jsr process_ws
	ldy #$00
@l0:	lda (zp::line),y
	bne :+
@err:   RETURN_ERR ERR_UNEXPECTED_CHAR	; line ended without ':'
:	jsr is_newl
	beq @err
	cmp #':'
	beq @cont			; found end of section name
	sta (@name),y
	iny
	cpy #MAX_SEGMENT_NAME_LEN
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG	; section name > 8 chars

@cont:	tya
	;sec			; +1 (move pointer after the ':')
	adc zp::line
	sta zp::line
	bcc @check_duplicate
	inc zp::line+1

@check_duplicate:
	; numsegments does not include the segment currently being parsed
	lda numsegments
	beq @getprops
	ldxy @name
	jsr get_segment_by_name
	bcs @getprops
	RETURN_ERR ERR_DUPLICATE_NAME

; read all properties defined for the SEGMENT
@getprops:
	jsr process_ws		; move the key name in segment

	ldy #$00
	lda (zp::line),y
	cmp #';'		; are we at the end of the segment?
	bne :+
	lda parsed_properties
	and #SEGMENT_PROPS_REQUIRED
	cmp #SEGMENT_PROPS_REQUIRED
	beq @properties_ok
	RETURN_ERR ERR_MISSING_REQUIRED_KEY

@properties_ok:
	; RUN defaults to LOAD when omitted
	lda parsed_properties
	and #SEGMENT_PROP_RUN
	bne @properties_done
	ldx numsegments
	lda segments_load,x
	sta segments_run,x

@properties_done:
	incw zp::line		; move beyond the semicolon
	RETURN_OK		; we're at the end, return

:	; read the key of the k/v pair into keybuffer
	ldxy #@keybuff
	jsr readkey
	bcs @err

@keyfound:
	ldxy #@keybuff
	stxy zp::str0

	; find the key that corresponds to the one in the config file
	ldxy #@keys
	stxy zp::str2

	lda #$00
	sta @cnt
@findkey:
	jsr strcmp
	bne @next

@found: ; found the key, run the command to map it
	ldx @cnt
	lda @cmdslo,x
	sta zp::jmpvec
	lda @cmdshi,x
	sta zp::jmpvec+1

	; read the value that the key is assigned into a temp buffer
	ldy #$00
:	lda (zp::line),y
	beq @get_section
	cmp #';'
	beq @get_section
	jsr is_ws
	beq @get_section
	sta @valbuff,y
	iny
	bne :-

@get_section:
	lda #$00
	sta @valbuff,y	; terminate the section name buffer

	; update line pointer to after the name that was read
	tya
	clc
	adc zp::line
	sta zp::line
	bcc :+
	inc zp::line+1

:	; run the handler for the given key
	jsr zp::jmpaddr
	jcc @getprops		; repeat (get next key if there is one)
	jcs log_error

@next:	; move zp::str2 to the next key to check
	ldy #$00
:	lda (zp::str2),y
	incw zp::str2
	cmp #$00
	bne :-

	; are we out of keys?
	inc @cnt
	lda @cnt
	cmp #@numkeys
	bne @findkey
	RETURN_ERR ERR_UNKNOWN_KEY	; no key matched the one in the file

;-------------------------------------------------------------------------------
; handler for the "run" key in SEGMENT
@runvec:
	; get the section ID
	ldxy #@valbuff
	jsr get_section_by_name
	bcc :+
	lda #ERR_UNKNOWN_SEGMENT	; section not found -> rts
	rts

:	; set the run section for the segment
	ldx numsegments
	sta segments_run,x
	lda parsed_properties
	ora #SEGMENT_PROP_RUN
	sta parsed_properties
	RETURN_OK

;-------------------------------------------------------------------------------
; handler for the "load" key in SEGMENT
@loadvec:
	; get the section ID
	ldxy #@valbuff
	jsr get_section_by_name
	bcc :+
	lda #ERR_UNKNOWN_SEGMENT	; section not found -> rts
	rts

:	; set the load section for the segment
	ldx numsegments
	sta segments_load,x
	lda parsed_properties
	ora #SEGMENT_PROP_LOAD
	sta parsed_properties
	RETURN_OK

;-------------------------------------------------------------------------------
; handler for the "align" key in SEGMENT
@alignvec:
	ldxy #@valbuff
	jsr parse_num			; get the requested alignment
	bcs @badalign			; not a number -> error

	stxy @alignval
	lda @alignval
	ora @alignval+1
	beq @badalign			; ALIGN=0 is not an alignment

	; the SEGMENT is aligned to at least this; the .ALIGN directives in the
	; objects that use it may raise it further (see link::require_align)
	ldx numsegments
	lda @alignval
	sta segments_alignlo,x
	lda @alignval+1
	sta segments_alignhi,x
	RETURN_OK

@badalign:
	RETURN_ERR ERR_INVALID_ALIGNMENT

;-------------------------------------------------------------------------------
; handler for the "define" key in SEGMENT
@definevec:
	ldxy #@valbuff
	jsr parse_num
	bcs @define_done
	cpy #$00
	bne @baddefine
	cpx #$02
	bcs @baddefine
	txa
	ldx numsegments
	sta segments_flags,x
	RETURN_OK
@baddefine:
	RETURN_ERR ERR_INVALID_EXPRESSION
@define_done:
	rts

;-------------------------------------------------------------------------------
; keys table
@numkeys=4
@keys:
@load:  .byte "load",0
@run:   .byte "run",0
@align: .byte "align",0
	.byte "define",0

;-------------------------------------------------------------------------------
; keys table handler vectors
.define seg_cmds @loadvec, @runvec, @alignvec, @definevec
@cmdslo: .lobytes seg_cmds
@cmdshi: .hibytes seg_cmds

.endproc

;*******************************************************************************
; VALIDATE SYMBOLS
; Validates that all symbols are resolved
; OUT:
;   - .C: set on error
.proc validate_symbols
@i=zp::tmp10
@seg_id=zp::tmp12
@obj_seg_offsets=zp::tmp14
@namebuff=$100
	iszero lbl::num
	beq @ok

	; iterate through all labels
	lda #$00
	sta @i
	sta @i+1

@l0:	jsr update_progress
	ldxy @i
	CALLMAIN lbl::getsegment		; get segment ID
	cmp #SEG_UNDEF				; is segment UNDEFINED?
	beq @err				; if so, error
	incw @i
	ldxy @i
	cmpw lbl::num
	bne @l0

@ok:	RETURN_OK
@err:	RETURN_ERR ERR_LABEL_UNDEFINED
.endproc

;*******************************************************************************
; RESOLVE SYMBOLS
; Adds each symbol's fragment RUN address to its offset after layout.
; Uses the owning object and local fragment ID to locate the fragment.
; Skips absolute, floating-point, and undefined symbols.
.proc resolve_symbols
@fragment=r0
@i=zp::tmp10
@seg=zp::tmp12
@mode=zp::tmp13
@base=zp::tmp14
	iszero lbl::num
	jeq @done
	lda #0
	sta @i
	sta @i+1
@loop:
	jsr update_progress
	ldxy @i
	CALLMAIN lbl::getsegment
	cmp #SEG_UNDEF
	beq @next
	cmp #SEG_ABS
	beq @next
	cmp #SEG_FLOAT
	beq @next
	sta @seg
	ldxy @i
	CALL FINAL_BANK_SYMBOLS, sympage::link_owner_get
	tay
	lda @seg
	sec
	sbc #1
	jsr object_fragment_ptr
	ldy #FR_RUNLO
	lda (@fragment),y
	sta @base
	iny
	lda (@fragment),y
	sta @base+1
	ldxy @i
	CALLMAIN lbl::addrmode
	sta @mode
	ldxy @i
	CALLMAIN lbl::getaddr
	txa
	clc
	adc @base
	sta zp::label_value
	tya
	adc @base+1
	sta zp::label_value+1
	; mark the resolved symbol as absolute
	lda #SEG_ABS
	sta zp::label_segmentid
	lda @mode
	sta zp::label_mode
	ldxy @i
	CALLMAIN lbl::setaddr
@next:
	incw @i
	ldxy @i
	cmpw lbl::num
	bne @loop
@done:
	RETURN_OK
.endproc

;*******************************************************************************
; CALC SEG ORIGINS
; Calculates the LOAD and RUN start addresses for each global SEGMENT.
; SEGMENTs are packed into their SECTION in LINK-file order.  The LOAD and RUN
; layouts are packed independently: a SEGMENT occupies space in the SECTION it
; LOADs to (where its bytes go in the output image) and, separately, in the
; SECTION it RUNs in (the address its code is relocated for).  For the common
; case where RUN and LOAD name the same SECTION the two layouts are identical.
; IN:
;   - Section, segment, and fragment tables from link pass 1.
; OUT:
;   - Fixed LOAD/RUN addresses in the segment and fragment tables.
;   - .C: set on error
calc_seg_origins: JUMP FINAL_BANK_LINKER_AUX, calculate_segment_origins
.pushseg
BANKED_SEG "LINKER_AUX", FINAL_BANK_LINKER_AUX

;*******************************************************************************
; CALCULATE SEGMENT ORIGINS
; Assigns LOAD and RUN addresses to segments and their fragments.
; IN:
;   - Section, segment, and fragment tables from link pass 1
; OUT:
;   - .C: set and .A = error code on failure
.proc calculate_segment_origins
@fill_start = r2
@cursorlo = section_cursorlo
@cursorhi = section_cursorhi
@value   = r0
@padding = r4
@load    = r6
@run     = r8
@seg     = ra
@frag    = rb
@fill    = rd
	ldx numsections
	jeq @ok

@init:	dex
	lda #$00
	sta section_cursorbank,x
	lda sections_startlo,x
	sta @cursorlo,x
	lda sections_starthi,x
	sta @cursorhi,x
	cpx #$00
	bne @init
	stx @seg

;-------------------------------------------------------------------------------
; set LOAD and RUN addresses for SEGMENT by looking up current cursor values
@segment:
	CALL FINAL_BANK_LINKER, __link_update_progress
	ldx @seg
	cpx numsegments
	jcs @validate
	lda segments_load,x
	CALL FINAL_BANK_LINKER_AUX, linkimage_select_section
	ldx @seg
	ldy segments_run,x
	lda @cursorlo,y
	sta @run
	lda @cursorhi,y
	sta @run+1
	lda section_cursorbank,y
	sta layout_runbank

	ldy segments_load,x
	lda @cursorlo,y
	sta @load
	lda @cursorhi,y
	sta @load+1
	lda section_cursorbank,y
	sta layout_loadbank

;-------------------------------------------------------------------------------
; apply ALIGNment for the segment (if it has any)
	lda segments_alignlo,x
	sta m::arg
	lda segments_alignhi,x
	sta m::arg+1

	; Exhausted sections retain their endpoint until the fragment check.
	ldxy @run
	lda layout_runbank
	clc
	bne :+
	CALL FINAL_BANK_EXPR, m::align_up
:	jcs @overflow
	stxy @run

	ldxy @load
	lda layout_loadbank
	clc
	bne :+
	CALL FINAL_BANK_EXPR, m::align_up
:	jcs @overflow
	stxy @value			; set stop address for fill

	lda #$00
	sta @fill			; init fill value to 0
	ldx @seg
	ldy segments_load,x
	lda sections_flags,y
	and #SECTION_NOEMIT
	bne @setbase			; address-only alignment emits no padding
	lda segments_type,x
	cmp #TYPE_UNDEF
	beq @setbase			; unused layout entries allocate addresses only
	cmp #TYPE_SEGZP
	beq @setbase			; don't fill ZP segments
	cmp #TYPE_BSS
	beq @setbase
	cmp #TYPE_BSSZP
	beq @setbase			; don't fill BSS segments
	ldxy @load
	stxy @fill_start
	CALL FINAL_BANK_LINKER, fill_span
	jcs @overflow			; fill from [@fill_start, @value)

;-------------------------------------------------------------------------------
@setbase:
	ldxy @value
	stxy @load
	ldx @seg
	lda @load
	sta segments_addrlo,x
	lda @load+1
	sta segments_addrhi,x
	lda layout_loadbank
	sta segments_addrbank,x
	lda @run
	sta segments_runaddrlo,x
	lda @run+1
	sta segments_runaddrhi,x
	lda layout_runbank
	sta segments_runaddrbank,x
	ldxy #fragments
	stxy @frag

;-------------------------------------------------------------------------------
@fragment:
	CALL FINAL_BANK_LINKER, __link_update_progress
	ldxy @frag
	cmpw fragments_top
	jcs @finish
	ldy #FR_SEGMENT
	lda (@frag),y
	sec
	sbc #$01
	cmp @seg
	jne @next

	lda layout_loadbank
	ora layout_runbank
	jne @overflow

	; apply fragment-level alignment (.align directives in the obj code)
	ldy #FR_ALIGNLO
	lda (@frag),y
	sta m::arg
	ldy #FR_ALIGNHI
	lda (@frag),y
	sta m::arg+1
	ldxy @run
	CALL FINAL_BANK_EXPR, m::align_up
	jcs @overflow
	stxy @value
	txa
	sec
	sbc @run
	sta @padding

	tya
	sbc @run+1
	sta @padding+1
	ldxy @value
	stxy @run
	lda @load
	clc
	adc @padding
	sta @load

	lda @load+1
	adc @padding+1
	sta @load+1
	jcs @overflow
	lda @padding
	ldy #FR_PADLO
	sta (@frag),y
	lda @padding+1
	ldy #FR_PADHI
	sta (@frag),y

	lda @load
	ldy #FR_LOADLO
	sta (@frag),y
	lda @load+1
	ldy #FR_LOADHI
	sta (@frag),y
	lda @run
	ldy #FR_RUNLO
	sta (@frag),y
	lda @run+1
	ldy #FR_RUNHI
	sta (@frag),y

	ldy #FR_SIZELO
	lda (@frag),y
	sta @value
	ldy #FR_SIZEHI
	lda (@frag),y
	sta @value+1
	ldy #FR_SIZEBANK
	lda (@frag),y
	sta layout_sizebank

	jsr advance_layout
	jcs @overflow


@next:	NEXT_FRAGMENT @frag
	jmp @fragment

;-------------------------------------------------------------------------------
@finish:
	ldx @seg
	lda @run
	sec
	sbc segments_runaddrlo,x
	sta segments_sizelo,x
	lda @run+1
	sbc segments_runaddrhi,x
	sta segments_sizehi,x
	lda layout_runbank
	sbc #$00
	sta segments_sizebank,x

	ldy segments_run,x
	lda section_cursorbank,y
	beq :+
	lda #$00
	sta segments_sizebank,x

:	ldy segments_load,x
	lda @load
	sta @cursorlo,y
	lda @load+1
	sta @cursorhi,y
	lda layout_loadbank
	sta section_cursorbank,y

	ldy segments_run,x
	lda @run
	sta @cursorlo,y
	lda @run+1
	sta @cursorhi,y
	lda layout_runbank
	sta section_cursorbank,y
	inc @seg
	jmp @segment

;-------------------------------------------------------------------------------
@validate:
	ldx #$00
@check:	cpx numsections
	beq @ok
	lda sections_stoplo,x
	cmp @cursorlo,x
	lda sections_stophi,x
	sbc @cursorhi,x
	lda sections_stopbank,x
	sbc section_cursorbank,x
	bcc @small
	inx
	bne @check
@ok:	RETURN_OK
@small:	RETURN_ERR ERR_SECTION_TOO_SMALL
@overflow:
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc

;*******************************************************************************
; ADVANCE LAYOUT
; Adds the given value to the LOAD and RUN cursors.
; IN:
;   - r0/r1, layout_sizebank: 24-bit amount to add to LOAD and RUN cursors
;   - r6/r7: LOAD cursor
;   - r8/r9: RUN cursor
; OUT:
;   - .C: set if either cursor exceeds $10000
.proc advance_layout
@size = r0
@load = r6
@run  = r8
	lda @load
	clc
	adc @size
	sta @load
	lda @load+1
	adc @size+1
	sta @load+1
	lda layout_loadbank
	adc layout_sizebank
	sta layout_loadbank
	bcs @overflow
	beq @run_cursor
	cmp #$01
	bne @overflow
	lda @load
	ora @load+1
	bne @overflow

@run_cursor:
	lda @run
	clc
	adc @size
	sta @run
	lda @run+1
	adc @size+1
	sta @run+1
	lda layout_runbank
	adc layout_sizebank
	sta layout_runbank
	bcs @overflow
	beq @ok
	cmp #$01
	bne @overflow
	lda @run
	ora @run+1
	bne @overflow

@ok:	clc
	rts

@overflow:
	sec
	rts
.endproc

.popseg
SET_CUR_BANK FINAL_BANK_LINKER

;*******************************************************************************
; FILL SPAN
; Fills the selected output range, preserving absolute objects.
; IN:
;   - r2: start address
;   - r0: exclusive end address
;   - rd: fill byte
; OUT:
;   - .C: set and .A = error code on failure
.proc fill_span
@stop   = r0
@cursor = r2
@fill   = rd

@loop:	jsr update_progress
	lda @cursor
	cmp @stop
	lda @cursor+1
	sbc @stop+1
	bcs @done
	jsr skip_absolute
	bcc @store
	lda @cursor
	ora @cursor+1
	beq @done
	jmp @loop

@store:	lda @fill
	ldxy @cursor
	jsr output_store
	bcc :+
	rts
:	incw @cursor
	jmp @loop

@done:	clc
	rts
.endproc

;*******************************************************************************
; UPDATE PROGRESS
; Calls the editor's UPDATE PROGRESS routine to indicate that the linker
; is still working.
.export __link_update_progress
__link_update_progress:
.proc update_progress
@saved=r0
	lda @saved
	pha
	lda @saved+1
	pha

	CALL FINAL_BANK_EDIT, edit::update_progress

	pla
	sta @saved+1
	pla
	sta @saved
	rts
.endproc

;*******************************************************************************
; FRAGMENT
; Registers an object's fragment during pass 1 and looks it up during pass 2.
; IN:
;   - .A = named segment ($ff for ABS)
;   - .X = object-local fragment index.
; OUT:
;   - .XY: global fragment record pointer
;   - .C: set if the fragment table is full or the fragment does not match
.export __link_fragment
.proc __link_fragment
	JUMP FINAL_BANK_LINKER_AUX, register_fragment
.endproc

;*******************************************************************************
; OBJECT FRAGMENT POINTER
; Locates a fragment record within its owning object.
; IN:
;   - .A: zero-based local fragment index
;   - .Y: one-based object ID
; OUT:
;   - .XY, r0: global fragment record pointer
.proc object_fragment_ptr
	JUMP FINAL_BANK_LINKER_AUX, fragment_pointer
.endproc
.pushseg
BANKED_SEG "LINKER_AUX", FINAL_BANK_LINKER_AUX

;*******************************************************************************
; REGISTER FRAGMENT
; Registers or looks up a fragment in the active object.
; IN:
;   - .A: named segment ($ff for ABS)
;   - .X: object-local fragment index
; OUT:
;   - .XY: global fragment record pointer
;   - .C: set if the table is full or the fragment does not match
.proc register_fragment
@parent = re
@local = rf
@ptr = r0
	sta @parent
	stx @local
	lda linkpass
	cmp #$02
	jeq @lookup
	ldxy fragments_top
	stxy @ptr
	cmpw #fragments_end
	jcs @full
	ldx @local
	bne @append
	ldy activeobj
	lda @ptr
	sta object_fragbase_lo-1,y
	lda @ptr+1
	sta object_fragbase_hi-1,y
@append:
	ldy #FR_BYTES-1
	lda #$00
@clear:	sta (@ptr),y
	dey
	bpl @clear
	ldy #FR_SEGMENT
	lda @parent
	sta (@ptr),y
	iny
	lda obj::segments_sizelo,x
	sta (@ptr),y
	iny
	lda obj::segments_sizehi,x
	sta (@ptr),y
	iny
	lda obj::segments_sizebank,x
	sta (@ptr),y
	iny
	lda obj::alignlo,x
	sta (@ptr),y
	iny
	lda obj::alignhi,x
	sta (@ptr),y
	iny
	lda obj::fill,x
	sta (@ptr),y
	lda @parent
	cmp #SEG_ABS
	bne @added
	ldy #FR_LOADLO
	lda obj::segments_startlo,x
	sta (@ptr),y
	ldy #FR_RUNLO
	sta (@ptr),y
	ldy #FR_LOADHI
	lda obj::segments_starthi,x
	sta (@ptr),y
	ldy #FR_RUNHI
	sta (@ptr),y
@added:	NEXT_FRAGMENT fragments_top
	ldxy @ptr
	clc
	rts
@lookup:
	lda @local
	ldy activeobj
	jsr fragment_pointer
	cmpw fragments_top
	jcs @full
	ldy #FR_SEGMENT
	lda (@ptr),y
	cmp @parent
	bne @invalid
	ldx @local
	ldy #FR_SIZELO
	lda (@ptr),y
	cmp obj::segments_sizelo,x
	bne @invalid

	iny
	lda (@ptr),y
	cmp obj::segments_sizehi,x
	bne @invalid

	iny
	lda (@ptr),y
	cmp obj::segments_sizebank,x
	bne @invalid

	ldxy @ptr
	clc
	rts

@invalid:
	RETURN_ERR ERR_IO_ERROR
@full:	RETURN_ERR ERR_TOO_MANY_SEGMENTS
.endproc

;*******************************************************************************
; FRAGMENT POINTER
; Adds a local fragment's record offset to its owning object's base pointer.
; IN:
;   - .A: zero-based local fragment index
;   - .Y: one-based object ID
; OUT:
;   - .XY, r0: global fragment record pointer
.proc fragment_pointer
@ptr=r0
.assert FR_BYTES = 16, error, "fragment pointer scaling assumes 16-byte records"
	ldx #0
	stx @ptr+1
	asl
	rol @ptr+1
	asl
	rol @ptr+1
	asl
	rol @ptr+1
	asl
	rol @ptr+1
	clc
	adc object_fragbase_lo-1,y
	sta @ptr
	lda @ptr+1
	adc object_fragbase_hi-1,y
	sta @ptr+1
	ldxy @ptr
	rts
.endproc

.popseg
SET_CUR_BANK FINAL_BANK_LINKER

;*******************************************************************************
; OWN SYMBOL
; Records the active object after a successful symbol definition.
; IN:
;   - .XY: symbol ID
;   - .C: set if the definition failed; skips the owner update
; OUT:
;   - .C: unchanged
.export __link_own_symbol
.proc __link_own_symbol
	bcs @ret
	lda activeobj
	CALL FINAL_BANK_SYMBOLS, sympage::link_owner_set
@ret:
	rts
.endproc

;*******************************************************************************
; PAD FRAGMENT
; Write the alignment bytes immediately preceding the given global fragment
; IN:
;   - .XY: global fragment record pointer
; OUT:
;   - .C: set and .A = error code on failure
.export __link_pad_fragment
.proc __link_pad_fragment
@start = r2
@stop = r0
@fill = rd
@ptr = re
	stxy @ptr
	CALL FINAL_BANK_LINKER_AUX, linkimage_select_fragment
	ldy #FR_SEGMENT
	lda (@ptr),y
	cmp #SEG_ABS
	beq @done
	tay

	lda segments_type-1,y
	cmp #TYPE_SEGZP
	beq @done
	cmp #TYPE_BSS
	beq @done
	cmp #TYPE_BSSZP
	beq @done

	ldy #FR_LOADLO
	lda (@ptr),y
	sta @stop
	sec
	ldy #FR_PADLO
	sbc (@ptr),y
	sta @start
	ldy #FR_LOADHI
	lda (@ptr),y
	sta @stop+1
	ldy #FR_PADHI
	sbc (@ptr),y
	sta @start+1
	ldy #FR_FILL
	lda (@ptr),y
	sta @fill
	jmp fill_span

@done:	clc
	rts
.endproc

;*******************************************************************************
; FILLED BOUNDS
; Includes the complete CPU address range of each filled output section.
; IN:
;   - Section flags and exclusive endpoints
; OUT:
;   - asm::origin, asm::top, asm::has_output: initialized CPU bounds
.proc filled_bounds
@section=r0
@last=re
	lda #$00
	sta @section
@loop:	ldx @section
	cpx numsections
	jcs @done
	lda sections_flags,x
	and #SECTION_FILL
	jeq @next_section
	lda @section
	jsr is_zp_section
	jeq @next_section
	ldx @section
	lda sections_stopbank,x
	bne @nonempty_section
	lda sections_startlo,x
	cmp sections_stoplo,x
	bne @nonempty_section
	lda sections_starthi,x
	cmp sections_stophi,x
	jeq @next_section

@nonempty_section:
	lda #$01
	sta asm::has_output
	lda sections_stoplo,x
	sec
	sbc #$01
	sta @last
	lda sections_stophi,x
	sbc #$00
	sta @last+1

	; include the entire filled SECTION in the CPU bounds
	ldx @section
	lda sections_starthi,x
	cmp asm::origin+1
	bcc @set_origin
	bne @check_top
	lda sections_startlo,x
	cmp asm::origin
	bcs @check_top

@set_origin:
	lda sections_startlo,x
	sta asm::origin
	lda sections_starthi,x
	sta asm::origin+1

@check_top:
	lda @last
	cmp asm::top
	lda @last+1
	sbc asm::top+1
	bcc @next_section
	lda @last
	sta asm::top
	lda @last+1
	sta asm::top+1

@next_section:
	inc @section
	jmp @loop
@done:	rts
.endproc

;*******************************************************************************
; SKIP ABSOLUTE
; Advances the given address past the absolute SEGMENT range that contains it,
; if any.  The ranges are those collected from the object headers during pass 1
; (see add_absolute_segment).
; IN:
;   - r2: the address to check
; OUT:
;   - r2: the address, advanced to the END of the ABS range that contained it
;   - .C: set if the address was advanced
.proc skip_absolute
@addr=r2
@ptr=r4
	ldxy #absolute_ranges
	stxy @ptr

@l0:	ldxy @ptr
	cmpw absolute_end
	beq @done		; end of table -> addr is in no ABS range

	; addr < range.start -> not in this range
	ldy #$00
	lda @addr
	cmp (@ptr),y
	iny
	lda @addr+1
	sbc (@ptr),y
	bcc @next

	; A zero exclusive endpoint denotes $10000.
	ldy #$02
	lda (@ptr),y
	iny
	ora (@ptr),y
	beq @inside

	; addr >= range.stop -> not in this range
	ldy #$02
	lda @addr
	cmp (@ptr),y
	iny
	lda @addr+1
	sbc (@ptr),y
	bcs @next

@inside:
	; addr is within the range; move it to the range's END
	ldy #$02
	lda (@ptr),y
	sta @addr
	iny
	lda (@ptr),y
	sta @addr+1
	sec			; address was advanced
	rts

@next:	; move to the next 4-byte range record
	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @l0
	inc @ptr+1
	jmp @l0

@done:	clc			; address was not in any ABS range
	rts
.endproc

;*******************************************************************************
; IS ZP SECTION
; Returns .Z set if any SEGMENT LOADs into the given SECTION as a zeropage
; SEGMENT.
; IN:
;   - .A: the id of the SECTION to test
; OUT:
;   - .Z: set if the SECTION is a zeropage SECTION
.proc is_zp_section
@section=r4
@i=r5
	sta @section
	lda #$00
	sta @i
	cmp numsegments
	beq @no			; no SEGMENTs -> not a zeropage SECTION

@l0:	ldx @i
	lda segments_load,x
	cmp @section
	bne @next		; SEGMENT doesn't load here

	lda segments_type,x
	eor #TYPE_SEGZP
	beq @yes
	lda segments_type,x
	eor #TYPE_BSSZP
	beq @yes

@next:	inc @i
	ldx @i
	cpx numsegments
	bcc @l0

@no:	lda #$01		; .Z clear -> not a zeropage SECTION
	rts

@yes:	lda #$00		; .Z set -> zeropage SECTION
	rts
.endproc

;*******************************************************************************
; Display and log the current object filename for either linker pass.
.proc report_linking_file
@objfile=zp::link+2
	; copy the current object filename from linker RAM into the shared buffer
	ldy #0
:	lda (@objfile),y
	sta link_filename,y
	beq :+
	iny
	bne :-
:	ldxy #link_filename
	lda linkpass
	CALL FINAL_BANK_EDIT, edit::linking_file
	ldxy #link_filename
	JUMPMAIN log::out
.endproc

;*******************************************************************************
; LINK
; Links all files in link::objfiles into the output image.
; IN:
;  - link::objfiles: array of the files to link (0-terminated)
; OUT:
;  - .C: set on error
;  - image::mode: $02 when the image is complete, $01 on failure
.export __link_link
.proc __link_link
@objfile=zp::link+2	; pointer to current object file being linked
@i=zp::link+4
@segname=zp::link+6
@tab=zp::link+8
	lda #$01
	sta image::mode		; invalidate the previous image before pass 1
	; init the segment/section pointers using the current linker state
	; (parsed from the LINK file prior to calling this procedured)
	ldx numsegments
	bne @init
	RETURN_ERR ERR_NO_SEGMENTS	; nothing to link into

@init:  ; initialize state:
	; labels (global symbol table)
	; debug info (global debug info)
	CALLMAIN lbl::clr
	CALLMAIN dbgi::init

	jsr init_segments
	ldxy #fragments
	stxy fragments_top

	; init obj pointer to start of object list
	ldxy #__link_objfiles
	stxy @objfile

	lda #$01
	sta activeobj
	sta linkpass		; the object headers are read for pass 1

;-------------------------------------------------------------------------------
; PASS1
; Extract header data foreach file and update pointers to each file to the main
; block of the .O file.
; Also define labels for the globals (IMPORT/EXPORT blocks) defined in each
; object file.
	jsr log_banner
	ldxy #strings::pass1
	RENDER_STR
	CALLMAIN log::out
	jsr log_banner

@pass1: ; display and log the object filename for this pass
	jsr report_linking_file

	; load the next .O (object) file in the object list
	ldxy @objfile
	stxy obj::filename
	ldxy #link_filename
	CALLMAIN file::open_r
	jcs log_error			; failed to open object file -> error
	pha				; save file handle
	tax
	jsr krn::chkin			; CHKIN
	jsr obj::load_headers	; get section sizes and add global labels
	sta objerr		; save error code
	pla			; restore file handle
	php			; save .C (error)
	CALLMAIN file::close	; close the object file
	plp			; restore load_headers error
	lda objerr		; restore error code
	jcs log_error

	jsr update_segments
	jcs log_error

@nextfile:
	jsr log_newl

	; next file; update filename pointer to next filename
	ldy #$01		; start search at 2nd character of filename
:	lda (@objfile),y	; get a char
	beq :+			; if 0, we've found terminator -> continue
	iny			; next char
	bne :-			; repeat til we've found 0

:	tya
	clc
	adc @objfile
	sta @objfile
	bcc :+
	inc @objfile+1
:	ldy #$01
	lda (@objfile),y	; get char after the terminating 0
	beq @pass1done		; if it's another 0, we're at end of obj list
	incw @objfile		; move to the next filename

	lda activeobj
	cmp #MAX_OBJS
	bcc :+
	lda #ERR_TOO_MANY_OBJECTS
	jmp log_error
:	inc activeobj
	jmp @pass1		; if not, repeat for next obj file
;-------------------------------------------------------------------------------

@pass1done:
	CALL FINAL_BANK_LINKER_AUX, linkimage_prepare
	jcs log_error
	; Layout reuses the now-dead @objfile pointer's scratch window.
	jsr calc_seg_origins
	jcs log_error
	jsr validate_segments
	jcs log_error

	; now that SEGMENT origins are known, finalize the values of the
	; symbols that were registered (segment-relative) during pass 1
	ldxy #@resolving_symbols
	jsr log_msg
	jsr resolve_symbols
	jcs log_error
	CALL FINAL_BANK_LINKER_AUX, define_layout_symbols
	jcs log_error

@start_pass2:
	jsr log_banner
	ldxy #strings::pass2
	RENDER_STR
	CALLMAIN log::out
	jsr log_banner

	; reset obj pointer to start of object list
	ldxy #__link_objfiles
	stxy @objfile
	lda #$01
	sta activeobj
	lda #$02
	sta linkpass		; the headers are read again for pass 2

;-------------------------------------------------------------------------------
; PASS2
; iterate over each object file again, but this time link it to to produce the
; final binary.
@pass2:	jsr report_linking_file

	ldxy #link_filename
	jsr link_object		; link the object file
	bcs log_error		; if .C set, return with error

	jsr log_newl

	; update filename pointer to next filename
	ldy #$0
:	lda (@objfile),y
	beq :+
	iny
	bne :-

:	tya
	clc
	adc @objfile
	sta @objfile
	bcc :+
	inc @objfile+1

:	inc activeobj

	ldy #$01
	lda (@objfile),y	; are we done? (0 at end of file list)
	beq @pass2done
	incw @objfile
	jmp @pass2		; repeat for all object files

;-------------------------------------------------------------------------------
@pass2done:
	; Fragment and segment origins remain fixed throughout pass 2.
	; calculate ORIGIN and TOP of linked program
	jsr image_bounds
	jsr filled_bounds	; include reserved output fill in the CPU bounds

	lda asm::has_output
	bne :+
	sta asm::origin
	sta asm::origin+1
:

	jsr validate_symbols
	bcs log_error

	CALLMAIN lbl::index	; finish symbol sorting before offering the map
	jsr prompt_map
	bcs log_error
	lda image::mapped
	bne @complete
	ldxy asm::origin
	stxy image::start
@complete:
	lda #$02
	sta image::mode
	RETURN_OK


@resolving_symbols: .byte "resolving symbols",0
.endproc

;*******************************************************************************
; LOG ERROR
; Logs the error given
; IN:
;   - .A: error code to log
.proc log_error
	pha
	CALLMAIN err::get
	CALLMAIN log::out
	pla
	sec
	rts			; return err
.endproc

;*******************************************************************************
; LINK OBJECT
; Produces the final binary for a given object file
; IN:
;   - .XY: address of the object filename to link
.proc link_object
@err=objerr	; NOTE: must survive file::close (which may clobber r0-r15)
	CALLMAIN file::open_r
	bcs @ret		; failed to open the object file -> error

	pha			; save file ID
	tax
	jsr krn::chkin		; CHKIN
	jsr obj::load		; load the object file with the given index

	sta @err
	pla			; restore file ID
	php			; save error flag
	CALLMAIN file::close

	plp			; restore error flag
	lda @err		; restore error code (if any)
@ret:	rts
.endproc

;*******************************************************************************
; INIT SEGMENTS
; Initializes segment addresses to 0
.proc init_segments
	ldx numsegments
	lda #$00
@l0:	sta segments_addrlo-1,x
	sta segments_addrhi-1,x
	sta segments_runaddrlo-1,x
	sta segments_runaddrhi-1,x
	dex
	bne @l0
	rts
.endproc

;*******************************************************************************
; UPDATE SEGMENTS
; Record absolute ranges. Relative usage is retained by link::fragment.
; OUT:
;   - .C: set if absolute SEGMENTs overlap or cannot be recorded
.proc update_segments
	ldx #$00
	cpx obj::numsegments
	beq @done

:	ldy obj::segment_ids,x		; get GLOBAL SEGMENT id from local one
	cpy #SEG_ABS			; ABS segments have no global SEGMENT
	bne @next

	; Preserve the local index while the absolute range is recorded.
	txa
	pha
	jsr add_absolute_segment
	sta objerr
	pla
	tax
	lda objerr
	bcs @ret

@next:	inx
	cpx obj::numsegments
	bne :-
@done:	RETURN_OK
@ret:	rts
.endproc

;*******************************************************************************
; ADD ABSOLUTE SEGMENT
; Adds a nonempty absolute SEGMENT range from the current object to the global
; absolute-range table. Errors on overlap with an earlier absolute SEGMENT.
; IN:
;   - .A: object-local SEGMENT index
; OUT:
;   - .C: set on overlap or if the range table is full
add_absolute_segment: JUMP FINAL_BANK_LINKER_AUX, register_absolute_segment
.pushseg
BANKED_SEG "LINKER_AUX", FINAL_BANK_LINKER_AUX

;*******************************************************************************
; REGISTER ABSOLUTE SEGMENT
; Records a nonempty absolute fragment after checking its range and overlaps
; IN:
;   - .A: object-local fragment index
; OUT:
;   - .C: set and .A = error code for invalid or overlapping ranges
.proc register_absolute_segment
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
@ptr=ra
	tax
	lda obj::segments_sizelo,x
	ora obj::segments_sizehi,x
	ora obj::segments_sizebank,x
	jeq @ok				; empty SEGMENTs cannot overlap

	lda obj::segments_startlo,x
	sta @addr0_start
	ldy obj::segments_starthi,x
	sty @addr0_start+1
	clc
	adc obj::segments_sizelo,x
	sta @addr0_stop
	tya
	adc obj::segments_sizehi,x
	sta @addr0_stop+1
	lda obj::segments_sizebank,x
	adc #$00
	jcs @outofrange
	beq @compare_init
	cmp #$01
	jne @outofrange
	lda @addr0_stop+1
	ora @addr0_stop
	jne @outofrange			; endpoint exceeds $10000

@compare_init:

	ldxy #absolute_ranges
	stxy @ptr
@compare:
	ldxy @ptr
	cmpw absolute_end
	beq @store

	ldy #$00
	lda (@ptr),y
	sta @addr1_start
	iny
	lda (@ptr),y
	sta @addr1_start+1
	iny
	lda (@ptr),y
	sta @addr1_stop
	iny
	lda (@ptr),y
	sta @addr1_stop+1
	CALL FINAL_BANK_LINKER, ranges_overlap
	bcs @overlap

	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @compare
	inc @ptr+1
	jmp @compare

@store:
	ldxy absolute_end
	cmpw #absolute_ranges_end
	bcs @too_many

	ldy #$00
	lda @addr0_start
	sta (@ptr),y
	iny
	lda @addr0_start+1
	sta (@ptr),y
	iny
	lda @addr0_stop
	sta (@ptr),y
	iny
	lda @addr0_stop+1
	sta (@ptr),y

	lda absolute_end
	clc
	adc #$04
	sta absolute_end
	bcc @ok
	inc absolute_end+1

@ok:	RETURN_OK
@overlap:
	RETURN_ERR ERR_OVERLAPPING_SEGMENTS
@too_many:
	RETURN_ERR ERR_TOO_MANY_SEGMENTS
@outofrange:
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc
.popseg
SET_CUR_BANK FINAL_BANK_LINKER


;*******************************************************************************
; IMAGE BOUNDS
; Finds the lowest LOAD address and highest end address across fragments.
; Includes initialized alignment padding; skips BSS, zeropage and empty fragments.
; Sets asm::origin and inclusive asm::top, with asm::has_output marking data.
; IN:
;   - Fragment table with fixed LOAD addresses and padding.
; OUT:
;   - None
image_bounds: JUMP FINAL_BANK_LINKER_AUX, calculate_image_bounds
.pushseg
BANKED_SEG "LINKER_AUX", FINAL_BANK_LINKER_AUX

;*******************************************************************************
; CALCULATE IMAGE BOUNDS
; Finds the loadable address range, including leading alignment padding.
; Sets asm::origin and inclusive asm::top, with asm::has_output marking data.
; IN:
;   - Fragment table with fixed LOAD addresses and padding
; OUT:
;   - None
.proc calculate_image_bounds
@start=r0
@stop=r2
@ptr=r4
	ldxy #$ffff
	stxy asm::origin
	ldxy #$00
	stxy asm::top
	stx asm::has_output
	ldxy #fragments
	stxy @ptr
@loop:	ldxy @ptr
	cmpw fragments_top
	jeq @done
	ldy #FR_SIZELO
	lda (@ptr),y
	ldy #FR_SIZEHI
	ora (@ptr),y
	ldy #FR_SIZEBANK
	ora (@ptr),y
	ldy #FR_PADLO
	ora (@ptr),y
	ldy #FR_PADHI
	ora (@ptr),y
	beq @next
	ldy #FR_SEGMENT
	lda (@ptr),y
	tay
	cpy #SEG_ABS
	beq @include
	lda segments_type-1,y
	cmp #TYPE_SEGZP
	beq @next
	cmp #TYPE_BSSZP
	beq @next
	cmp #TYPE_BSS
	beq @next
@include:
	lda #$01
	sta asm::has_output
	ldy #FR_LOADLO
	lda (@ptr),y
	sec
	ldy #FR_PADLO
	sbc (@ptr),y
	sta @start
	ldy #FR_LOADHI
	lda (@ptr),y
	ldy #FR_PADHI
	sbc (@ptr),y
	sta @start+1
	ldy #FR_LOADLO
	lda (@ptr),y
	clc
	ldy #FR_SIZELO
	adc (@ptr),y
	sta @stop
	ldy #FR_LOADHI
	lda (@ptr),y
	ldy #FR_SIZEHI
	adc (@ptr),y
	sta @stop+1
	decw @stop		; convert the exclusive endpoint to the last byte

	lda @start
	cmp asm::origin
	lda @start+1
	sbc asm::origin+1
	bcs @maximum
	lda @start
	sta asm::origin
	lda @start+1
	sta asm::origin+1
@maximum:
	lda @stop
	cmp asm::top
	lda @stop+1
	sbc asm::top+1
	bcc @next
	lda @stop
	sta asm::top
	lda @stop+1
	sta asm::top+1
@next:	NEXT_FRAGMENT @ptr
	jmp @loop
@done:	rts
.endproc
.popseg
SET_CUR_BANK FINAL_BANK_LINKER

;*******************************************************************************
; GET SECTION BY NAME
; Returns the ID of the section from its name
; IN:
;  - .XY: the name of the section
; OUT:
;  - .A: the ID of the section
;  - .C: set if no segment exists by the given name
.proc get_section_by_name
	stxy zp::str0
	ldxy #section_names
	lda numsections
	jmp find_name
.endproc



;*******************************************************************************
; SET SEGMENT TYPE
; Sets the type for the segment of the given ID.
; IN:
;   - .A: type to set
;   - .X: id of segment to set type for
; OUT:
;   - .C: set on error (segment is defined with conflicting type)
.export __link_set_segment_type
.proc __link_set_segment_type
	ldy segments_type-1,x
	cpy #SEG_UNDEF		; is segment still undefined?
	beq @set		; if so, continue

	; segment exists, validate that its TYPE matches
	cmp segments_type-1,x
	beq @done
	RETURN_ERR ERR_CONFLICTING_SEGMENTS

@set:	sta segments_type-1,x
@done:	RETURN_OK
.endproc

;*******************************************************************************
; GET SEGMENT BY NAME
; Returns the ID of the segment from its name
; IN:
;  - .XY: the name of the segment
; OUT:
;  - .A: the ID of the segment
;  - .C: set if no segment exists by the given name
.export __link_get_segment_by_name
__link_get_segment_by_name:
.proc get_segment_by_name
	stxy zp::str0
	ldxy #segment_names
	lda numsegments
	jsr find_name
	bcs @missing
	adc #$01		; IDs for segments are 1-based
	rts
@missing:
	lda #ERR_UNKNOWN_SEGMENT
	rts
.endproc

;*******************************************************************************
; FIND NAME
; Seeks the given table of strings for the string to find.
; IN:
;   - .A:       max number of items to search
;   - .XY:      address of table to seek for name in
;   - zp::str0: address of string to look for in table
; OUT:
;   - .A: 0-based index
;   - .C: set if not found
.proc find_name
@other=zp::str2
@limit=r0
	stxy @other
	sta @limit
	ldx #$00

@loop:	cpx @limit
	bcs @done
	jsr strcmp		; preserves X
	beq @found
	lda @other
	clc
	adc #$08
	sta @other
	bcc :+
	inc @other+1
:	inx
	bne @loop
@found: txa
	clc
@done:	rts
.endproc

;*******************************************************************************
; READ KEY
; Read the key in a key/value pair into the given buffer
; A key/value pair is a string and value separated by an '=' sign
; IN:
;   - zp::line: the buffer to read the key from
;   - .XY:      the address to read the key into
; OUT:
;   - zp::line: updated to point after the '=' in the key/value pair
;   - .C:       set if the input buffer is not a valid key/value pair
.proc readkey
@buff=r0
	stxy @buff

	ldy #$00
@l0:	lda (zp::line),y
	jsr is_newl
	beq @err	; unexpected newline
	cmp #'='
	beq @done	; found end of key definition
	sta (@buff),y
	iny
	cpy #8
	bcc @l0
	RETURN_ERR ERR_LABEL_TOO_LONG

@done:	lda #$00
	sta (@buff),y	; terminate bufffer
	tya
	sec		; +1
	adc zp::line
	sta zp::line
	bcc :+
	inc zp::line+1
:	RETURN_OK

@err:	RETURN_ERR ERR_UNEXPECTED_CHAR
.endproc

;*******************************************************************************
; PARSE NUM
; Parses the number in the given 0-terminated buffer.  The number may be given
; in decimal or, with a '$' prefix, in hexadecimal.
; Reads a value copied from the LINK file by a SEGMENT key handler.
; IN:
;   - .XY: the buffer holding the number to parse
; OUT:
;   - .XY: the value that was parsed
;   - .C:  set if the buffer does not hold a valid number
.proc parse_num
@buff=r0
	stxy @buff
	ldy #$00
	lda (@buff),y
	cmp #'$'
	beq @hex

@dec:	ldxy @buff
	JUMPMAIN atoi

@hex:	incw @buff		; move over the '$'
	ldxy @buff
	JUMPMAIN util::parsehex
.endproc

;*******************************************************************************
; COMPARE LINE
; Compares the strings in (zp::line) and (.XY) up to a length of .A
.proc cmpline
	stxy zp::str2
	ldxy zp::line
	stxy zp::str0

	; fall through to strcmp
.endproc

;*******************************************************************************
; COMPARE
; Compares the strings in (zp::str0) and (zp::str2) up to a length of .A
; IN:
;  zp::str0: one of the strings to compare
;  zp::str2: the other string to compare
; OUT:
;  .Z: set if the strings are equal
.export __link_strcmp
__link_strcmp:
.proc strcmp
	ldy #$00
@l0:	lda (zp::str0),y
	beq :+
	jsr is_ws
	beq :+
	cmp (zp::str2),y
	bne @ret
	iny
	bne @l0

:	lda (zp::str2),y	; make sure strings terminate at same index
@ret:	rts
.endproc

;*******************************************************************************
; PROCESS WORD
; Advances the LINK text pointer to the next whitespace or NUL terminator.
; IN/OUT:
;   - zp::line: text pointer
.proc process_word
	ldy #0
@loop:
	lda (zp::line),y
	beq @done
	jsr is_ws
	beq @done
	incw zp::line
	jmp @loop
@done:
	rts
.endproc

;*******************************************************************************
; PROCESS WS
; Reads (line) and updates it to point past ' ' chars and non-printing chars
; out:
;  .Z: set if we're at the end of the line
;  .A: the last character processed
;  .Y: 0
;  zp::line: updated to first non ' ' character
.proc process_ws
	ldy #$00
@l0:	lda (zp::line),y
	beq @done		; if end of line, we're done
	bmi @skip		; skip non-printing chars
	jsr is_ws
	bne @done		; if not space, we're done
@skip:	incw zp::line
	bne @l0
@done:	rts
.endproc

;*******************************************************************************
; IS NEWL
; Checks if the given character is a newline ($0d or $0a)
; IN:
;  - .A: the character to test
; OUT:
;  - .Z: set if if the character in .A is whitespace
.proc is_newl
	cmp #$0d	; newline
	beq :+
	cmp #$0a	; UNIX newline
:	rts
.endproc

;*******************************************************************************
; IS WS
; Checks if the given character is a whitespace character
; IN:
;  - .A: the character to test
; OUT:
;  - .Z: set if if the character in .A is whitespace
.proc is_ws
	cmp #$0d	; newline
	beq :+
	cmp #$09	; TAB
	beq :+
	cmp #$0a	; UNIX newline
	beq :+
	cmp #' '
:	rts
.endproc

;*******************************************************************************
; PRINT STATUS
; Display a shared or MAIN-bank string on the editor's status row.
.proc print_status
	lda edit::status_row
	CALLMAIN text::print
	rts
.endproc

map_question: .byte "generate map? (", $79, "/", $6e, ")", 0

;*******************************************************************************
; PROMPT MAP
; Offer the optional map after the linked image has been validated.
; Unblank first so IRQ keyboard scanning runs while waiting for an answer.
.proc prompt_map
	CALLMAIN scr::unblank
	ldxy #map_question
	jsr copy_msg
	jsr print_status
	CALLMAIN key::flush		; ignore input typed during linking
@key:	CALLMAIN key::waitch
	cmp #K_QUIT
	beq @skip
	and #$df			; accept either case
	cmp #$59			; 'y'
	beq @map
	cmp #$4e			; 'n'
	bne @key

@skip:	ldxy #strings::null
	jsr print_status
	RETURN_OK

@map:	ldxy #strings::saving
	jsr print_status
	CALLMAIN scr::blank
	; fall through to generate_map
.endproc

;*******************************************************************************
; GENERATE MAP
; Write a "MAP" file containing all the SEGMENTS and SYMBOLS that were
; used in the creation of the linked program
.proc generate_map
@i=r2
@tmp=r4
@name=r6
@symbuff=lbl::namebuffer
	; check if there is already a MAP file
	ldxy #@filename
	CALLMAIN file::exists
	cmp #$00
	bne @new

	; scratch the existing MAP file if it exists
	ldxy #@filename
	CALLMAIN file::scratch
	bcs @err

@new:	ldxy #@filename
	CALLMAIN file::open_w
	bcc :+
@err:	rts

:	pha				; save file handle
	tax
	jsr krn::chkout			; CHKOUT

	lda #$00
	sta @i
	cmp numsegments
	jeq @symbols

@segments:
	ldxy #@seglist_title
	jsr puts		; write the "segments" title
	jsr write_h_line
	ldxy #@seglist_header
	jsr puts		; write the "segments" header

	; write the name, address, and size of each segment
	ldxy #segment_names
	stxy @name
	lda #$00
	sta @i

@segloop:
	jsr update_progress
	ldy #$00
:	lda (@name),y
	beq :+
	jsr krn::chrout
	iny
	cpy #MAX_SEGMENT_NAME_LEN
	bne :-

:	; write 8-len(name)+1 spaces of padding
	sty @tmp
	lda #8
	sec
	sbc @tmp
	tay
	lda #' '
:	jsr krn::chrout
	dey
	bpl :-

@segstart:
	ldx @i
	ldy segments_addrhi,x	; LOAD address (MSB)
	lda segments_addrlo,x	; LOAD address (LSB)
	tax
	jsr putword

	; padding between LOAD and RUN
	lda #' '
	jsr krn::chrout
	jsr krn::chrout

@segrun:
	ldx @i
	ldy segments_runaddrhi,x	; RUN address (MSB)
	lda segments_runaddrlo,x	; RUN address (LSB)
	tax
	jsr putword

	; padding between RUN and size
	lda #' '
	jsr krn::chrout
	jsr krn::chrout

@segsize:
	ldx @i
	lda segments_sizebank,x
	beq @wordsize

	lda #'$'
	jsr krn::chrout
	lda #'1'
	jsr krn::chrout
	lda #$00
	jsr puthex
	lda #$00
	jsr puthex
	jmp @nextseg

@wordsize:
	ldy segments_sizehi,x	; get the size (MSB)
	lda segments_sizelo,x	; get the size (LSB)
	tax
	jsr putword

@nextseg:
	lda #$0d
	jsr krn::chrout

	lda @name
	clc
	adc #MAX_SEGMENT_NAME_LEN
	sta @name
	bcc :+
	inc @name+1

:	inc @i
	lda @i
	cmp numsegments
	jne @segloop

@symbols:
	lda #$0d
	jsr krn::chrout

	ldxy #@symbols_title
	jsr puts		; write the "symbols" title
	jsr write_h_line
	ldxy #@symbols_header
	jsr puts		; write the "symbols" header

	; write the name, address, and address mode of each symbol
	ldxy #$00
	stxy @i
	cmpw lbl::num
	beq @done

@symloop:
	jsr update_progress
	ldxy #@symbuff
	stxy r0
	ldxy @i
	CALLMAIN lbl::getname
	ldxy #@symbuff
	jsr puts

	; Pad short names to column 33; long names get one separating space.
	lda #' '
:	jsr krn::chrout
	cpy #32
	bcs @symbol_addr
	iny
	bne :-
@symbol_addr:

	; write the label's address
	ldxy @i
	CALLMAIN lbl::addr_and_mode
	cmp #$00					; zeropage?
	beq @zp
@abs:	jsr putword
	jmp @nextsym
@zp:	jsr putbyte
@nextsym:
	lda #$0d
	jsr krn::chrout
	incw @i
	ldxy @i
	cmpw lbl::num
	bne @symloop

@done:	pla					; restore file handle
	CALLMAIN file::close
	JUMPMAIN file::geterr			; report write errors
						; (e.g. disk full)

;-------------------------------------------------------------------------------
@seglist_title:  .byte "segments",$0d,0
@seglist_header: .byte "name     load   run    size",$0d,0
@symbols_title:  .byte "symbols",$0d,0
@symbols_header: .byte "name                             addr",$0d,0

.PUSHSEG
.RODATA
@filename:       .byte "map",0
.POPSEG
.endproc

;*******************************************************************************
; VALIDATE SEGMENTS
; Checks if any named or absolute segments generated during linking overlap
; IN:
;   - Segment and absolute range tables with fixed addresses
;   - image::mapped: explicit image offsets rather than CPU address layout
; OUT:
;   - .A: error code (if validation failed)
;   - .C: set if any two segments overlap
.proc validate_segments
@i=r0
@j=r1
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
@ptr=ra
	lda numsegments
	jeq @ok

	lda #$00
	sta @i

@l0:	jsr update_progress
	ldx @i
	; skip empty segments (they can't overlap anything)
	lda segments_sizelo,x
	ora segments_sizehi,x
	ora segments_sizebank,x
	beq @nexti

	lda segments_addrlo,x
	sta @addr0_start
	ldy segments_addrhi,x
	sty @addr0_start+1
	clc
	adc segments_sizelo,x
	sta @addr0_stop
	tya
	adc segments_sizehi,x
	sta @addr0_stop+1

	ldx @i
	stx @j

@l1:	inc @j
	ldx @j
	cpx numsegments
	bcs @nexti

	; skip empty segments
	lda segments_sizelo,x
	ora segments_sizehi,x
	ora segments_sizebank,x
	beq @l1

	lda segments_addrlo,x
	sta @addr1_start
	ldy segments_addrhi,x
	sty @addr1_start+1
	clc
	adc segments_sizelo,x
	sta @addr1_stop
	tya
	adc segments_sizehi,x
	sta @addr1_stop+1

	lda image::mapped
	beq :+
	ldx @i
	lda segments_load,x
	ldx @j
	cmp segments_load,x
	bne @l1
:	jsr ranges_overlap
	bcs @overlap
	bcc @l1			; branch always

@nexti:	inc @i
	lda @i
	cmp numsegments
	bcc @l0

	; compare all absolute ranges with every named global SEGMENT now that
	; their origins are known
	ldxy #absolute_ranges
	stxy @ptr
@absolute_loop:
	jsr update_progress
	ldxy @ptr
	cmpw absolute_end
	beq @ok

	ldy #$00
	lda (@ptr),y
	sta @addr0_start
	iny
	lda (@ptr),y
	sta @addr0_start+1
	iny
	lda (@ptr),y
	sta @addr0_stop
	iny
	lda (@ptr),y
	sta @addr0_stop+1

	lda #$00
	sta @j
@absolute_global_loop:
	ldx @j
	lda segments_sizelo,x
	ora segments_sizehi,x
	ora segments_sizebank,x
	beq @next_absolute_global

	lda segments_addrlo,x
	sta @addr1_start
	ldy segments_addrhi,x
	sty @addr1_start+1
	clc
	adc segments_sizelo,x
	sta @addr1_stop
	tya
	adc segments_sizehi,x
	sta @addr1_stop+1

	jsr ranges_overlap
	bcs @overlap

@next_absolute_global:
	inc @j
	lda @j
	cmp numsegments
	bcc @absolute_global_loop

	lda @ptr
	clc
	adc #$04
	sta @ptr
	bcc @absolute_loop
	inc @ptr+1
	jmp @absolute_loop

@ok:	RETURN_OK

@overlap:
	RETURN_ERR ERR_OVERLAPPING_SEGMENTS
.endproc

;*******************************************************************************
; RANGES OVERLAP
; Checks whether two nonempty address ranges overlap
; NOTE: 0 means $10000.
; IN:
;   - r2/r3: first range start
;   - r4/r5: first range exclusive end
;   - r6/r7: second range start
;   - r8/r9: second range exclusive end
; OUT:
;   - .C: set if the ranges overlap
.proc ranges_overlap
@addr0_start = r2
@addr0_stop  = r4
@addr1_start = r6
@addr1_stop  = r8
	lda @addr1_stop
	ora @addr1_stop+1
	beq @second		; if stop is 0 it is $10000

	; if addr0.start >= addr1.stop, no overlap
	lda @addr0_start
	cmp @addr1_stop
	lda @addr0_start+1
	sbc @addr1_stop+1
	bcs @no_overlap

@second:
	lda @addr0_stop
	ora @addr0_stop+1
	beq @overlap

	; if addr1.start >= addr0.stop, no overlap
	lda @addr1_start
	cmp @addr0_stop
	lda @addr1_start+1
	sbc @addr0_stop+1
	bcs @no_overlap

@overlap:
	sec			; overlap
	rts

@no_overlap:
	clc
	rts
.endproc

;*******************************************************************************
; WRITE H LINE
; Writes a line of '-'s
.proc write_h_line
	lda #'-'
	ldy #LINESIZE
:	jsr krn::chrout
	dey
	bne :-
	lda #$0d
	jmp krn::chrout
.endproc

;*******************************************************************************
; PUTBYTE
; Outputs the given byte as a hex value
; IN:
;   - .X: the value to output
.proc putbyte
	lda #'$'
	jsr krn::chrout
	txa

	; fall through to puthex
.endproc

;*******************************************************************************
; PUTHEX
; Writes two hex digits to the open file
; IN:
;   - .A: byte to write out (as hex digits)
.proc puthex
	CALLMAIN util::hextostr
	tya
	jsr krn::chrout
	txa
	jmp krn::chrout
.endproc

;*******************************************************************************
; PUTWORD
; Outputs the given word in a '$' prefixed hex value
; IN:
;   - .XY: the word to ouput in hex digits
.proc putword
	txa
	pha
	tya
	tax
	jsr putbyte
	pla
	jmp puthex
.endproc

;*******************************************************************************
; PUTS
; Writes a 0-terminated string to the open file
; IN:
;   - .XY: the address of the string to output
; OUT:
;   - .Y: the length of the string written
.proc puts
@str=zp::str0
	stxy @str

	ldy #$00
:	lda (@str),y
	beq @done
	jsr krn::chrout
	iny
	bne :-

@done:	rts
.endproc

;*******************************************************************************
; LOG NEWL
; Logs a newline
.proc log_newl
	ldxy #strings::null
	JUMPMAIN log::out
.endproc

;*******************************************************************************
; COPY MSG
; Copies the given message to shared RAM for display
; IN:
;   - .XY: message
; OUT:
;   - .XY: copy of message in shared RAM
.proc copy_msg
@str=r4
@buff=$100
	stxy @str
	ldy #$ff
:	iny
	lda (@str),y
	sta @buff,y
	bne :-
	ldxy #@buff
	rts
.endproc

;*******************************************************************************
; LOG MSG
; Copies the provided string to shared RAM and logs it
; IN:
;   - .XY: address of string to log
.export __link_log_msg
__link_log_msg:
.proc log_msg
@ret=r4
	jsr copy_msg

	pla
	sta @ret
	pla
	sta @ret+1

	RENDER_STR			; render the string
	lda @ret+1
	pha
	lda @ret
	pha
	JUMPMAIN log::out
.endproc

;*******************************************************************************
; LOG BANNER
; Logs a '*' banner
.export __link_log_banner
__link_log_banner:
.proc log_banner
	JUMPMAIN log::banner
.endproc

;*******************************************************************************
; CAPITALIZE
; Capitalizes the input character
; IN:
;   - .A: character to capitalize
; OUT:
;   - .A: capitalized version of input character
.proc capitalize
	cmp #$61
	bcc @done
	cmp #$7a+1
	bcs @done
	eor #$20	; to upper
@done:	rts
.endproc

;*******************************************************************************
; LOAD OUTPUT
; Reads a byte from the output image.
; IN:
;   - .XY: CPU LOAD address in the selected output section.
; OUT:
;   - .A: byte, or error code when .C is set.
.export __link_output_load
.proc __link_output_load
	JUMP FINAL_BANK_LINKER_AUX, linkimage_load
.endproc

;*******************************************************************************
; STORE OUTPUT
; Writes a byte to the output image.
; IN:
;   - .A: byte
;   - .XY: CPU LOAD address in the selected output section.
; OUT:
;   - .C: set and .A = error code on failure.
.export __link_output_store
.proc __link_output_store
	JUMP FINAL_BANK_LINKER_AUX, linkimage_store
.endproc
output_store = __link_output_store

;*******************************************************************************
; LINK IMAGE
; Section layout and access for banked linker output.
.segment "LINKER_VARS"
output_delta:    .res 3
output_xy:       .word $0000
output_byte:     .byte $00
image_value:     .res 3
image_digit:     .byte $00
image_digits:    .byte $00
image_radix:     .byte $00
image_i:         .byte $00
image_j:         .byte $00
meta_segment:    .byte $00
meta_kind:       .byte $00
meta_existing:   .byte $00
meta_mode:       .byte $00
section_endlo:   .res MAX_SECTIONS
section_endhi:   .res MAX_SECTIONS
section_endbank: .res MAX_SECTIONS

BANKED_SEG "LINKER_AUX", FINAL_BANK_LINKER_AUX

;*******************************************************************************
; PARSE SECTION PROPERTY
; Reads one numeric MEMORY property and records its layout attributes.
; IN:
;   - .X:       START, END, FILL, OFFSET, EMIT, or BANK property index
;   - zp::line: property value
; OUT:
;   - .C: set and .A = error code on invalid input
.proc parse_section_property
	cpx #$02
	bcs :+
	jmp parse_section_address
:	cpx #$03
	bne :+
	jmp linkimage_parse_offset
:	txa
	pha
	jsr parse_section_value
	bcc :+
	pla
	RETURN_ERR ERR_INVALID_EXPRESSION
:	pla
	tay
	ldx numsections
	cpy #$05
	beq @bank
	cpy #$04
	beq @emit

	lda image_value
	ora image_value+1
	ora image_value+2
	beq @clear_fill
	lda sections_flags,x
	ora #SECTION_FILL
	bne @flags
@clear_fill:
	lda sections_flags,x
	and #($ff ^ SECTION_FILL)
	jmp @flags

@emit:	lda image_value+1
	ora image_value+2
	bne @bad
	lda image_value
	cmp #$02
	bcs @bad
	cmp #$00
	bne @emitting
	lda sections_flags,x
	ora #SECTION_NOEMIT
	bne @flags
@emitting:
	lda sections_flags,x
	and #($ff ^ SECTION_NOEMIT)
@flags:
	sta sections_flags,x
	RETURN_OK

@bank:	lda image_value+2
	bne @bad
	lda image_value
	sta sections_banklo,x
	lda image_value+1
	sta sections_bankhi,x
	RETURN_OK
@bad:	RETURN_ERR ERR_INVALID_EXPRESSION
.endproc

;*******************************************************************************
; DEFINE LAYOUT SYMBOLS
; Publishes absolute constants for segments marked DEFINE=1. Each 24-bit
; value has a low-word symbol and an upper-byte HI symbol.
; IN:
;   - Final segment addresses, sizes, and memory bank numbers
; OUT:
;   - .C: set and .A = error code on a conflicting name or exhausted symbols
.proc define_layout_symbols
@name = $100
@ptr = r0
@suffix = r2
	lda #$00
	sta meta_segment
@segment:
	ldx meta_segment
	cpx numsegments
	jcs @done
	lda segments_flags,x
	and #SEGMENT_DEFINE
	jeq @next
	lda #$00
	sta meta_kind

@symbol:
	; Copy the fixed-width segment name and append the property suffix.
	lda #$00
	sta @ptr+1
	lda meta_segment
	asl
	rol @ptr+1
	asl
	rol @ptr+1
	asl
	rol @ptr+1
	clc
	adc #<segment_names
	sta @ptr
	lda @ptr+1
	adc #>segment_names
	sta @ptr+1
	ldy #$00
@copy:	lda (@ptr),y
	beq @append
	sta @name,y
	iny
	cpy #MAX_SEGMENT_NAME_LEN
	bcc @copy
@append:
	tya
	tax
	ldy meta_kind
	lda @suffixlo,y
	sta @suffix
	lda @suffixhi,y
	sta @suffix+1
	ldy #$00
@tail:	lda (@suffix),y
	sta @name,x
	beq @value
	inx
	iny
	bne @tail

@value:	jsr layout_symbol_value
	lda #$01
	sta meta_mode
	lda #$00
	sta meta_existing
	ldxy #@name
	CALLMAIN lbl::find
	bcs @define
	inc meta_existing
	CALLMAIN lbl::getsegment
	cmp #SEG_UNDEF
	jne @conflict
	ldxy #@name
	CALLMAIN lbl::find
	CALLMAIN lbl::addrmode
	sta meta_mode
	bne @define
	lda zp::label_value+1
	jne @mode_error

@define:
	lda #SEG_ABS
	sta zp::label_segmentid
	lda meta_mode
	sta zp::label_mode
	lda #$ff
	sta zp::label_fileid
	lda #$00
	sta zp::label_lineno
	sta zp::label_lineno+1
	ldxy #@name
	lda meta_existing
	beq @add
	CALLMAIN lbl::set
	jmp @result
@add:	CALLMAIN lbl::add
@result:
	bcs @ret
	inc meta_kind
	lda meta_kind
	cmp #$08
	jne @symbol
@next:	inc meta_segment
	jmp @segment
@done:	RETURN_OK
@conflict:
	RETURN_ERR ERR_ALREADY_EXPORTED
@mode_error:
	RETURN_ERR ERR_ADDRMODE_MISMATCH
@ret:	rts

;-------------------------------------------------------------------------------
@load:    .byte ".load",0
@run:     .byte ".run",0
@size:    .byte ".size",0
@loadhi:  .byte ".loadhi",0
@runhi:   .byte ".runhi",0
@sizehi:  .byte ".sizehi",0
@bank:    .byte ".bank",0
@runbank: .byte ".runbank",0
.define metadata_names @load, @run, @size, @loadhi, @runhi, @sizehi, @bank, @runbank
@suffixlo: .lobytes metadata_names
@suffixhi: .hibytes metadata_names
.endproc

;*******************************************************************************
; LAYOUT SYMBOL VALUE
; Selects one field of the current segment's final layout.
; IN:
;   - meta_segment: zero-based segment index
;   - meta_kind: layout property index
; OUT:
;   - zp::label_value: unsigned word value
.proc layout_symbol_value
@ptr = r0
	lda #$00
	sta zp::label_value+1
	ldx meta_kind
	cpx #$06
	bcs @bank
	lda @tableslo,x
	sta @ptr
	lda @tableshi,x
	sta @ptr+1
	ldy meta_segment
	lda (@ptr),y
	sta zp::label_value
	cpx #$03
	bcs @done
	lda @wordlo,x
	sta @ptr
	lda @wordhi,x
	sta @ptr+1
	lda (@ptr),y
	sta zp::label_value+1
@done:	rts

@bank:	ldy meta_segment
	cpx #$06
	bne @run
	ldx segments_load,y
	jmp @readbank
@run:	ldx segments_run,y
@readbank:
	lda sections_banklo,x
	sta zp::label_value
	lda sections_bankhi,x
	sta zp::label_value+1
	rts

.define metadata_tables segments_addrlo, segments_runaddrlo, segments_sizelo, segments_addrbank, segments_runaddrbank, segments_sizebank
@tableslo: .lobytes metadata_tables
@tableshi: .hibytes metadata_tables
.define metadata_words segments_addrhi, segments_runaddrhi, segments_sizehi
@wordlo: .lobytes metadata_words
@wordhi: .hibytes metadata_words
.endproc

;*******************************************************************************
; PARSE SECTION VALUE
; Parses a decimal or hexadecimal 24-bit MEMORY property.
; IN:
;   - zp::line: value text
; OUT:
;   - image_value: parsed 24-bit value
;   - zp::line: after the value
;   - .C: set and .A = error code on invalid input.
.proc parse_section_value
	CALL FINAL_BANK_LINKER, process_ws
	lda #$00
	sta image_value
	sta image_value+1
	sta image_value+2
	sta image_digits
	lda #$0a
	sta image_radix
	ldy #$00
	lda (zp::line),y
	cmp #'$'
	bne @digit
	lda #$10
	sta image_radix
	incw zp::line

@digit:	ldy #$00
	lda (zp::line),y
	jeq @finish
	cmp #';'
	jeq @finish
	cmp #' '
	jeq @finish
	cmp #$09
	jeq @finish
	cmp #$0d
	jeq @finish
	cmp #$0a
	jeq @finish
	sec
	sbc #'0'
	bcc @bad
	cmp #$0a
	bcc @number
	sbc #$07
	cmp #$0a
	bcc @bad

@number:
	cmp image_radix
	bcs @bad
	sta image_digit

	; multiply the 24-bit value by the radix using checked additions
	lda image_value
	sta output_delta
	lda image_value+1
	sta output_delta+1
	lda image_value+2
	sta output_delta+2
	lda #$00
	sta image_value
	sta image_value+1
	sta image_value+2
	ldx image_radix

@multiply:
	clc
	lda image_value
	adc output_delta
	sta image_value
	lda image_value+1
	adc output_delta+1
	sta image_value+1
	lda image_value+2
	adc output_delta+2
	sta image_value+2
	bcs @bad
	dex
	bne @multiply
	clc
	lda image_value
	adc image_digit
	sta image_value
	lda image_value+1
	adc #$00
	sta image_value+1
	lda image_value+2
	adc #$00
	sta image_value+2
	bcs @bad
	lda #$01
	sta image_digits
	incw zp::line
	jmp @digit

@bad:	RETURN_ERR ERR_INVALID_EXPRESSION

@finish:
	lda image_digits
	beq @bad
	RETURN_OK
.endproc

;*******************************************************************************
; PARSE SECTION ADDRESS
; Stores a CPU address or exclusive endpoint for the current section and marks
; the corresponding required property as present
; IN:
;   - .X:       $00 for START, $01 for END
;   - zp::line: value text to parse
; OUT:
;   - zp::line: updated to point after the value
;   - .C:       set if parse failed
;   - .A:       error code (if .C is set)
.proc parse_section_address
	txa
	pha
	jsr parse_section_value
	bcc :+
	pla
	RETURN_ERR ERR_INVALID_EXPRESSION
:	pla
	tay

	ldx numsections
	lda image_value+2
	beq @store
	cpy #$01
	bne @bad
	cmp #$01
	bne @bad
	lda image_value
	ora image_value+1
	bne @bad

@store:	cpy #$00
	bne @end

	lda image_value
	sta sections_startlo,x
	lda image_value+1
	sta sections_starthi,x
	lda #SECTION_PROP_START
	bne @flag

@end:	lda image_value
	sta sections_stoplo,x
	lda image_value+1
	sta sections_stophi,x
	lda image_value+2
	sta sections_stopbank,x
	lda #SECTION_PROP_END

@flag:	ora parsed_properties
	sta parsed_properties
	RETURN_OK

@bad:	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc

;*******************************************************************************
; PARSE OFFSET
; Stores the current section's 24-bit output offset and selects image output
; IN:
;   - zp::line: value text
; OUT:
;   - zp::line: after the value
;   - .C:       set on error
;   - .A:       error code (if .C is set)
.proc linkimage_parse_offset
	jsr parse_section_value
	bcs @ret

	ldx numsections
	lda image_value
	sta sections_offsetlo,x
	lda image_value+1
	sta sections_offsethi,x
	lda image_value+2
	sta sections_offsetbank,x

	lda sections_flags,x
	ora #SECTION_OFFSET
	sta sections_flags,x

	; set MAPPED flag if offset was specified
	lda #$01
	sta image::mapped
	RETURN_OK

@ret:	rts
.endproc

;*******************************************************************************
; SELECT SECTION
; Computes the image displacement for a MEMORY section.
; IN:
;   - .A: section index.
; OUT:
;   - output_delta: 24-bit difference between OFFSET and START.
.proc linkimage_select_section
	tax
	sec
	lda sections_offsetlo,x
	sbc sections_startlo,x
	sta output_delta
	lda sections_offsethi,x
	sbc sections_starthi,x
	sta output_delta+1
	lda sections_offsetbank,x
	sbc #$00
	sta output_delta+2
	rts
.endproc

;*******************************************************************************
; SELECT FRAGMENT
; Selects the output section for a named fragment.
; IN:
;   - re: global fragment record pointer.
; OUT:
;   - output_delta: image displacement of the fragment's LOAD section.
.proc linkimage_select_fragment
@ptr = re
	ldy #FR_SEGMENT
	lda (@ptr),y
	cmp #SEG_ABS
	beq @done
	sec
	sbc #$01
	tax
	lda segments_load,x
	jmp linkimage_select_section

@done:	lda #$00
	sta output_delta
	sta output_delta+1
	sta output_delta+2
	rts
.endproc

;*******************************************************************************
; OUTPUT CURSOR
; Translates a CPU LOAD address to an image offset.
; IN:
;   - .XY: CPU address
;   - output_delta: selected section displacement
; OUT:
;   - image::cursor: 24-bit image offset
;   - output_xy:     original .XY
.proc output_cursor
	stx output_xy
	sty output_xy+1
	txa
	clc
	adc output_delta
	sta image::cursor
	tya
	adc output_delta+1
	sta image::cursor+1
	lda output_delta+2
	adc #$00
	sta image::cursor+2
	rts
.endproc

;*******************************************************************************
; LOAD OUTPUT
; Reads a byte from the output image.
; IN:
;   - .XY: CPU LOAD address
;   - output_delta: selected section displacement
; OUT:
;   - .A: byte, or error code when .C is set.
;   - .XY: original CPU LOAD address.
.proc linkimage_load
	jsr output_cursor
	jsr image::load
	ldxy output_xy
	rts
.endproc

;*******************************************************************************
; STORE OUTPUT
; Writes a byte to the output image.
; IN:
;   - .A: byte
;   - .XY: CPU LOAD address
;   - output_delta: selected section displacement
; OUT:
;   - .C: set and .A = error code on failure.
;   - .XY: original CPU LOAD address.
.proc linkimage_store
	sta output_byte
	jsr output_cursor
	lda output_byte
	jsr image::store
	ldxy output_xy
	rts
.endproc

;*******************************************************************************
; PREPARE IMAGE
; Validates section extents and initializes the banked output image.
; IN:
;   - Linker section and segment tables populated by pass 1.
; OUT:
;   - .C: set and .A = error code for invalid layout.
;   - image::length: end of any reserved FILL sections.
.proc linkimage_prepare
	lda #$00
	jsr image::init
	lda image::mapped
	bne @explicit
	; With no explicit offsets, CPU LOAD addresses are image offsets.
	ldx #$00
@defaults:
	cpx numsections
	beq @segments_begin
	lda sections_startlo,x
	sta sections_offsetlo,x
	lda sections_starthi,x
	sta sections_offsethi,x
	lda #$00
	sta sections_offsetbank,x
	lda sections_flags,x
	and #SECTION_FILL
	beq @next_default
	stx image_i
	txa
	CALL FINAL_BANK_LINKER, is_zp_section
	ldx image_i
	cmp #$00
	beq @next_default
	lda sections_flags,x
	ora #SECTION_OFFSET
	sta sections_flags,x
@next_default:
	inx
	bne @defaults

@explicit:
	ldxy #absolute_ranges
	cmpw absolute_end
	jne @absolute

@segments_begin:
	ldx #$00
@segments:
	cpx numsegments
	beq @sections
	lda segments_type,x
	cmp #TYPE_SEG
	beq @initialized
	cmp #TYPE_SEGZP
	bne @nextseg
@initialized:
	ldy segments_load,x
	lda sections_flags,y
	and #SECTION_NOEMIT
	beq :+
	RETURN_ERR ERR_CONFLICTING_SEGMENTS
:	lda image::mapped
	beq @nextseg
	lda sections_flags,y
	and #SECTION_OFFSET
	jeq @missing
@nextseg:
	inx
	bne @segments

@sections:
	lda #$00
	sta image_i

@bounds:
	ldx image_i
	cpx numsections
	jeq @pairs
	lda sections_flags,x
	and #SECTION_OFFSET
	beq @nextbound

	; image_value = sections_stop - sections_start
	sec
	lda sections_stoplo,x
	sbc sections_startlo,x
	sta image_value
	lda sections_stophi,x
	sbc sections_starthi,x
	sta image_value+1
	lda sections_stopbank,x
	sbc #$00
	sta image_value+2
	jcc @absolute

	; section_end = image_value + sections_offset
	clc
	lda sections_offsetlo,x
	adc image_value
	sta section_endlo,x
	lda sections_offsethi,x
	adc image_value+1
	sta section_endhi,x
	lda sections_offsetbank,x
	adc image_value+2
	sta section_endbank,x
	jcs @large
	cmp #.bankbyte(IMAGE_CAPACITY)
	bcc @nextbound
	jne @large
	lda section_endhi,x
	cmp #>IMAGE_CAPACITY
	bcc @nextbound
	jne @large
	lda section_endlo,x
	cmp #<IMAGE_CAPACITY
	bcc @nextbound
	jne @large

@nextbound:
	inc image_i
	jmp @bounds

@pairs:	lda image::mapped
	jeq @reserve
	lda #$00
	sta image_i

@outer:	ldx image_i
	cpx numsections
	jcs @reserve
	jsr section_has_offset_and_size
	beq @nexti
	stx image_j

@inner:	inc image_j
	ldx image_j
	cpx numsections
	bcs @nexti
	jsr section_has_offset_and_size
	beq @inner

	; i.start < j.end && j.start < i.end (24-bit subtraction)
	ldy image_i
	lda sections_offsetlo,y
	cmp section_endlo,x
	lda sections_offsethi,y
	sbc section_endhi,x
	lda sections_offsetbank,y
	sbc section_endbank,x
	bcs @inner
	lda sections_offsetlo,x
	cmp section_endlo,y
	lda sections_offsethi,x
	sbc section_endhi,y
	lda sections_offsetbank,x
	sbc section_endbank,y
	bcs @inner
	RETURN_ERR ERR_OVERLAPPING_SEGMENTS

@nexti:	inc image_i
	jmp @outer

@reserve:
	; write last byte
	lda #$00
	sta image_i
@fill:	ldx image_i
	cpx numsections
	beq @done
	jsr section_has_offset_and_size
	beq @nextfill
	lda sections_flags,x
	and #SECTION_FILL
	beq @nextfill

	; image::cursor = (section_end - 1)
	sec
	lda section_endlo,x
	sbc #$01
	sta image::cursor
	lda section_endhi,x
	sbc #$00
	sta image::cursor+1
	lda section_endbank,x
	sbc #$00
	sta image::cursor+2
	lda #$00
	jsr image::store
	bcc @nextfill
	rts

@nextfill:
	inc image_i
	jmp @fill

@done:	RETURN_OK

@large:	RETURN_ERR ERR_FILE_TOO_BIG

@missing:
	RETURN_ERR ERR_MISSING_REQUIRED_KEY

@absolute:
	RETURN_ERR ERR_SEGMENT_OUT_OF_RANGE
.endproc

;*******************************************************************************
; SECTION HAS OFFSET AND SIZE
; Tests whether a section has an OFFSET and a nonzero size.
; IN:
;   - .X: section index.
; OUT:
;   - .Z: clear for a nonempty section with OFFSET.
.proc section_has_offset_and_size
	lda sections_flags,x
	and #SECTION_OFFSET
	beq @done
	lda sections_stoplo,x
	eor sections_startlo,x
	bne @done
	lda sections_stophi,x
	eor sections_starthi,x
	bne @done
	lda sections_stopbank,x

@done:	rts
.endproc
